## Setup

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Set paths to data folders
path = Path.cwd()
input1_path = path / "Output_Data"
input2_path = path / "Output_Data" /"Updated_outputs"
output_path = path / "Deliverable"

In [3]:
writer = pd.ExcelWriter(output_path / "Givewell Output Tables.xlsx" , engine = 'openpyxl')

ModuleNotFoundError: No module named 'openpyxl'

## Per Country Combinations

### Data Cleaning
~ To match the admin level names in the charity submitted data

In [ ]:
nigeria_mc= pd.read_csv(input1_path/ "mc_nigeria_output.csv")
#names to rename
levels_renaming = {
    "Dange-Shuni" : "Dange Shuni",
    "Wamako" : "Wamakko",
    "Kala/Balge" : "Kala Balge",
    "Maiduguri" : "Maiduguri M.C.",
    "Arewa-Dandi" : "Arewa Dandi",
    "Barikin Ladi" : "Barkin Ladi",
    "Nasarawa-Eggon" : "Nasarawa Egon",
    "Askira/Uba" : "Askira-Uba",
    }

nigeria_mc["ADM2_EN"]=nigeria_mc["ADM2_EN"].replace(levels_renaming)
nigeria_mc.to_csv(input2_path / "clean_mc_nigeria_output.csv")

#### 1. Nigeria

Read outputs

In [ ]:
nigeria_mc_output= pd.read_csv(input2_path/ "clean_mc_nigeria_output.csv")
nigeria_mc_output

,Unnamed: 0,ADM1_EN,ADM2_EN,worldpop_cons_u5_nga_f_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_nga_m_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,worldpop_wopr_u5_sum,worldpop_wopr_3-59_months,facebook_u5_sum,facebook_3-59_months
0,0,Bauchi,Alkaleri,37571,36599,74170,70461.50,81989,77889.55,88787,84347.65
1,1,Bauchi,Bauchi,59878,58328,118206,112295.70,258402,245481.90,133585,126905.75
2,2,Bauchi,Bogoro,13240,12898,26138,24831.10,27681,26296.95,28951,27503.45
3,3,Bauchi,Damban,21510,20953,42463,40339.85,40404,38383.80,52379,49760.05
4,4,Bauchi,Darazo,38443,37448,75891,72096.45,86984,82634.80,95062,90308.90
...,...,...,...,...,...,...,...,...,...,...,...
137,137,Sokoto,Tangaza,11827,11521,23348,22180.60,52305,49689.75,28585,27155.75
138,138,Sokoto,Tureta,13005,12668,25673,24389.35,30338,28821.10,33207,31546.65
139,139,Sokoto,Wamakko,20269,19744,40013,38012.35,107611,102230.45,44341,42123.95
140,140,Sokoto,Wurno,22237,21661,43898,41703.10,61184,58124.80,52893,50248.35
141,141,Sokoto,Yabo,10028,9768,19796,18806.20,40017,38016.15,23030,21878.50

Read charity provided estimates

In [ ]:
nigeria_mc_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="MC Nigeria")

In [ ]:
nigeria_mc_data=nigeria_mc_data[["State","LGA","Submitted MC Data for Target Population(3M-59M) in 2021"]]
nigeria_mc_data

,State,LGA,Submitted MC Data for Target Population(3M-59M) in 2021
0,Sokoto,Binji,28726
1,Sokoto,Bodinga,37757
2,Sokoto,Dange Shuni,65736
3,Sokoto,Gada,68675
4,Sokoto,Goronyo,27237
...,...,...,...
127,Kogi,Yagba East,43755.1
128,Kogi,Yagba West,42393.75
129,NaN,Total,NaN
130,NaN,NaN,NaN
131,NaN,Source:,MC 2021 SMC Target Population

Rename column names

In [ ]:
nigeria_mc_output=nigeria_mc_output.rename(columns={"ADM1_EN":"State","ADM2_EN": "LGA"})

Use concat to combine

In [ ]:
nigeria_mc_merged = pd.merge(nigeria_mc_data, nigeria_mc_output, on=["State", "LGA"], how="left")
nigeria_mc_merged

,State,LGA,Submitted MC Data for Target Population(3M-59M) in 2021,Unnamed: 0,worldpop_cons_u5_nga_f_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_nga_m_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,worldpop_wopr_u5_sum,worldpop_wopr_3-59_months,facebook_u5_sum,facebook_3-59_months
0,Sokoto,Binji,28726,119.0,12835.0,12503.0,25338.0,24071.10,25616.0,24335.20,31811.0,30220.45
1,Sokoto,Bodinga,37757,120.0,22227.0,21652.0,43879.0,41685.05,71473.0,67899.35,53444.0,50771.80
2,Sokoto,Dange Shuni,65736,121.0,34538.0,33644.0,68182.0,64772.90,94696.0,89961.20,82540.0,78413.00
3,Sokoto,Gada,68675,122.0,23957.0,23337.0,47294.0,44929.30,108757.0,103319.15,58363.0,55444.85
4,Sokoto,Goronyo,27237,123.0,23546.0,22936.0,46482.0,44157.90,57566.0,54687.70,61018.0,57967.10
...,...,...,...,...,...,...,...,...,...,...,...,...
127,Kogi,Yagba East,43755.1,87.0,15498.0,15097.0,30595.0,29065.25,17070.0,16216.50,35183.0,33423.85
128,Kogi,Yagba West,42393.75,88.0,17285.0,16838.0,34123.0,32416.85,10122.0,9615.90,35326.0,33559.70
129,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,Source:,MC 2021 SMC Target Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Update WOPR estimates with growth factor

In [ ]:
nigeria_mc_merged["updated_wopr_3-59_months"]  =  nigeria_mc_merged["worldpop_wopr_3-59_months"]  * 1.0327

Calculate percentage differences

In [ ]:
nigeria_mc_merged["cons_perc_difference"]=((nigeria_mc_merged["worldpop_cons_3-59_months"]- nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])/nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])
nigeria_mc_merged["wopr_perc_difference"]=((nigeria_mc_merged["worldpop_wopr_3-59_months"]- nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])/nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])
nigeria_mc_merged["meta_perc_difference"]=((nigeria_mc_merged["facebook_3-59_months"]- nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])/ nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])

Save to file

In [ ]:
ordered_col_names=['State', 'LGA',
       'Submitted MC Data for Target Population(3M-59M) in 2021', 'worldpop_cons_3-59_months','cons_perc_difference',
       'worldpop_wopr_3-59_months', 'wopr_perc_difference', 'facebook_3-59_months',     'meta_perc_difference', "updated_wopr_3-59_months"]

In [ ]:
nigeria_mc_merged=nigeria_mc_merged[ordered_col_names]
nigeria_mc_merged

,State,LGA,Submitted MC Data for Target Population(3M-59M) in 2021,worldpop_cons_3-59_months,cons_perc_difference,worldpop_wopr_3-59_months,wopr_perc_difference,facebook_3-59_months,meta_perc_difference
0,Sokoto,Binji,28726,24071.10,-0.162045,24335.20,-0.152851,30220.45,0.052024
1,Sokoto,Bodinga,37757,41685.05,0.104035,67899.35,0.798325,50771.80,0.344699
2,Sokoto,Dange Shuni,65736,64772.90,-0.014651,89961.20,0.368523,78413.00,0.192847
3,Sokoto,Gada,68675,44929.30,-0.345769,103319.15,0.504465,55444.85,-0.192649
4,Sokoto,Goronyo,27237,44157.90,0.621247,54687.70,1.007846,57967.10,1.128248
...,...,...,...,...,...,...,...,...,...
127,Kogi,Yagba East,43755.1,29065.25,-0.335729,16216.50,-0.62938,33423.85,-0.236115
128,Kogi,Yagba West,42393.75,32416.85,-0.235339,9615.90,-0.773176,33559.70,-0.208381
129,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,Source:,MC 2021 SMC Target Population,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nigeria_mc_merged.to_excel(writer, sheet_name= "MC_Nigeria",index=False)

Read outputs

In [ ]:
chad_mc_output= pd.read_csv(input2_path/ "clean_mc_chad_output.csv")
chad_mc_output

,Unnamed: 0.1,Unnamed: 0,District,RegName,geometry,worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,tcd_children_under_five_2020,facebook_3-59_months
0,0,0,9e Arrondissement,N'Djamena,POLYGON Z ((15.04868549500003 12.0863161520000...,25241,24519,49760,47272.00,41802.962255,39712.814142
1,1,1,Abdi,Ouaddai,POLYGON Z ((21.310583000000065 13.160848000000...,17831,17321,35152,33394.40,33135.095590,31478.340811
2,2,2,Abeche,Ouaddai,POLYGON Z ((21.14911900000004 14.0312490000000...,36934,35878,72812,69171.40,81262.264047,77199.150845
3,3,3,Aboudeia,Salamat,POLYGON Z ((19.751000000000033 12.053000000000...,8153,7920,16073,15269.35,17095.805218,16241.014957
4,4,4,Abougoudam,Ouaddai,POLYGON Z ((21.352293607000036 13.256151919000...,13362,12980,26342,25024.90,19101.363908,18146.295713
...,...,...,...,...,...,...,...,...,...,...,...
121,121,121,Tissi,Sila,POLYGON Z ((22.554689410000037 11.694129940000...,10859,10549,21408,20337.60,5035.680548,4783.896521
122,122,122,Torrock,Mayo Kebbi Ouest,POLYGON Z ((15.114499000000023 9.5977830000000...,6469,6284,12753,12115.35,8579.589284,8150.609820
123,123,123,Yao,Batha,POLYGON Z ((17.450000000000045 13.497000000000...,13673,13282,26955,25607.25,36068.029965,34264.628467
124,124,124,Youe,Mayo Kebbi Est,POLYGON Z ((14.96474900000004 9.71562900000003...,7750,7528,15278,14514.10,5883.994225,5589.794514
125,125,125,Zouar,Tibesti,MULTIPOLYGON Z (((18.764079000000038 21.408342...,2838,2756,5594,5314.30,971.858062,923.265159

Read charity provided estimates

In [ ]:
chad_mc_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="MC Chad")

In [ ]:
chad_mc_data=chad_mc_data[["Region","Health District","Submitted Malaria Consortium Data for Target Population in 2017"]]
chad_mc_data

,Region,Health District,Submitted Malaria Consortium Data for Target Population in 2017
0,Bahr el Ghazal,Chadra,20484
1,Bahr el Ghazal,Michemere,9893
2,Bahr el Ghazal,Moussoro,38734
3,Bahr el Ghazal,Salal,10612
4,Batha,Yao,23619
5,Chari Baguirmi,Ba-Illi,36304
6,Chari Baguirmi,Bousso,33795
7,Chari Baguirmi,Dourbali,38661
8,Chari Baguirmi,Mandelia,62937
9,Chari Baguirmi,Massenya,36364
10,Chari Baguirmi,Kouno,11834
11,Hadjer Lamis,Bokoro,58183
12,Hadjer Lamis,Gama,19942
13,Hadjer Lamis,Karal,28499
14,Hadjer Lamis,Mani,23173
15,Hadjer Lamis,Massaguet,43175
16,Hadjer Lamis,Massakory,30937
17,Mayo Kebbi Est,Bongor,52165
18,Mayo Kebbi Est,Gam*,20418
19,Mayo Kebbi Est,Guelendeng,33520
20,Mayo Kebbi Est,Moulkou**,26287
21,N'Djamena,N'Djamena Centre,92011
22,N'Djamena,N'Djamena Est,108632
23,N'Djamena,N'Djamena Nord,69939
24,N'Djamena,N'Djamena Sud,106101
25,N'Djamena,Toukra,44347

Rename column names

In [ ]:
chad_mc_output=chad_mc_output.rename(columns={"District": "Health District",	"RegName" : "Region"})

Use concat to combine

In [ ]:
chad_mc_merged=pd.merge(chad_mc_data,chad_mc_output,on=["Health District"])
chad_mc_merged.columns

Index(['Region_x', 'Health District',
       'Submitted Malaria Consortium Data for Target Population in 2017',
       'Unnamed: 0.1', 'Unnamed: 0', 'Region_y', 'geometry',
       'worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'tcd_children_under_five_2020', 'facebook_3-59_months'],
      dtype='object')

Calculate percentage differences

In [ ]:
chad_mc_output.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Health District', 'Region', 'geometry',
       'worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'tcd_children_under_five_2020', 'facebook_3-59_months'],
      dtype='object')

In [ ]:
chad_mc_merged["cons_perc_difference"]  =  ((chad_mc_merged["worldpop_cons_3-59_months"]  -   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])  /  chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])
# chad_mc_merged["wopr_perc_difference"]  =  ((chad_mc_merged["worldpop_wopr_3-59_months"]  -   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])  /  chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])
chad_mc_merged["meta_perc_difference"]  =  ((chad_mc_merged["facebook_3-59_months"]  -   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])  /   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])

Save to file

In [ ]:
chad_mc_merged.columns

Index(['Region_x', 'Health District',
       'Submitted Malaria Consortium Data for Target Population in 2017',
       'Unnamed: 0.1', 'Unnamed: 0', 'Region_y', 'geometry',
       'worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'tcd_children_under_five_2020', 'facebook_3-59_months',
       'cons_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [ ]:
ordered_col_names = [
    'Region_x', 
    'Health District',
    'Submitted Malaria Consortium Data for Target Population in 2017',
    'worldpop_cons_3-59_months',
    'cons_perc_difference',
    'facebook_3-59_months',
    'meta_perc_difference'
]

In [ ]:
chad_mc_merged=chad_mc_merged[ordered_col_names]
chad_mc_merged

,Region_x,Health District,Submitted Malaria Consortium Data for Target Population in 2017,worldpop_cons_3-59_months,cons_perc_difference,facebook_3-59_months,meta_perc_difference
0,Bahr el Ghazal,Chadra,20484,19730.55,-0.036782,9754.000974,-0.523823
1,Bahr el Ghazal,Michemere,9893,14326.95,0.448191,7400.452971,-0.251951
2,Bahr el Ghazal,Moussoro,38734,24965.05,-0.355475,18157.754651,-0.531219
3,Bahr el Ghazal,Salal,10612,14591.05,0.374958,9933.624848,-0.063925
4,Batha,Yao,23619,25607.25,0.084180,34264.628467,0.450723
5,Chari Baguirmi,Ba-Illi,36304,16703.85,-0.539890,13565.317185,-0.626341
6,Chari Baguirmi,Bousso,33795,23779.45,-0.296362,20613.675398,-0.390038
7,Chari Baguirmi,Dourbali,38661,30780.00,-0.203849,30908.272043,-0.200531
8,Chari Baguirmi,Mandelia,62937,16892.90,-0.731590,12416.390493,-0.802717
9,Chari Baguirmi,Massenya,36364,21587.80,-0.406341,14120.190707,-0.611699
10,Chari Baguirmi,Kouno,11834,10893.65,-0.079462,7877.110233,-0.334366
11,Hadjer Lamis,Bokoro,58183,42039.40,-0.277462,35436.572461,-0.390946
12,Hadjer Lamis,Gama,19942,15557.20,-0.219878,12078.906625,-0.394298
13,Hadjer Lamis,Karal,28499,11461.75,-0.597819,8816.871976,-0.690625
14,Hadjer Lamis,Mani,23173,8934.75,-0.614433,8347.220198,-0.639787
15,Hadjer Lamis,Massaguet,43175,25882.75,-0.400515,18550.489307,-0.570342
16,Hadjer Lamis,Massakory,30937,27066.45,-0.125111,25018.238313,-0.191317
17,Mayo Kebbi Est,Bongor,52165,39944.65,-0.234263,46425.945558,-0.110017
18,Mayo Kebbi Est,Guelendeng,33520,17713.70,-0.471548,14164.909645,-0.577419
19,Mayo Kebbi Est,Moulkou**,26287,21625.80,-0.177320,11246.578656,-0.572162
20,N'Djamena,N'Djamena Centre,92011,34074.60,-0.629668,42580.760702,-0.537221
21,N'Djamena,N'Djamena Est,108632,52506.50,-0.516657,54102.953960,-0.501961
22,N'Djamena,N'Djamena Nord,69939,99268.35,0.419356,109916.442900,0.571604
23,N'Djamena,N'Djamena Sud,106101,58899.05,-0.444878,59161.855418,-0.442401

In [ ]:
chad_mc_merged.to_excel(writer, sheet_name="MC_Chad", index=False)

# Close

In [ ]:
writer.close()