## Setup

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Set paths to data folders
path = Path.cwd()
input1_path = path / "Output_Data"
input2_path = path / "Output_Data" /"Updated_outputs"
output_path = path / "Deliverable"

In [3]:
writer = pd.ExcelWriter(output_path / "Givewell Output Tables.xlsx" , engine = 'openpyxl')

## Per Country Combinations

### Data Cleaning
~ To match the admin level names in the charity submitted data

In [4]:
nigeria_mc= pd.read_csv(input1_path/ "mc_nigeria_output.csv")
#names to rename
levels_renaming = {
    "Dange-Shuni" : "Dange Shuni",
    "Wamako" : "Wamakko",
    "Kala/Balge" : "Kala Balge",
    "Maiduguri" : "Maiduguri M.C.",
    "Arewa-Dandi" : "Arewa Dandi",
    "Barikin Ladi" : "Barkin Ladi",
    "Nasarawa-Eggon" : "Nasarawa Egon",
    "Askira/Uba" : "Askira-Uba",
    }

nigeria_mc["ADM2_EN"]=nigeria_mc["ADM2_EN"].replace(levels_renaming)
nigeria_mc.to_csv(input2_path / "clean_mc_nigeria_output.csv")

In [5]:
chad_mc= pd.read_csv(input1_path/ "mc_chad_output.csv")
#names to rename
levels_renaming = {
    "Chaddra" : "Chadra",
    "Michemire" : "Michemere",
    "Ba Illi" : "Ba-Illi",
    "Moulkou" : "Moulkou**",
    "Ndjamena-Centre" : "N'Djamena Centre",
    "Ndjamena-Est" : "N'Djamena Est",
    "Ndjamena-Nord" : "N'Djamena Nord",
    "Ndjamena-Sud" : "N'Djamena Sud",    
    }

chad_mc["District"]=chad_mc["District"].replace(levels_renaming)
chad_mc.to_csv(input2_path / "clean_mc_chad_output.csv")

In [6]:
burkinafaso_mc= pd.read_csv(input1_path/ "mc_burkinafaso_output.csv")
#names to rename
levels_renaming = {
    "NONGR-MASSOUM" : "NONGR-MASSOM"  ,
    "KONGOUSSI" : "KOUNGOUSSI"  ,
    "PO" : "Pô",
    "SAPONE" : "Saponé",
    "DANDE" : "Dandé",
    "DO" : "Dô",
    "HOUNDE" : "Houndé",
    "KARANGASSO - VIGUE" : "Karangasso Vigué",
    "BOUSSE" : "Boussé",
    "ZINIARE" : "Ziniaré",
    }

burkinafaso_mc["NOMDEP"]=burkinafaso_mc["NOMDEP"].replace(levels_renaming)
burkinafaso_mc.to_csv(input2_path / "clean_mc_burkinafaso_output.csv")

In [7]:
kenya_hki= pd.read_csv(input1_path/ "hki_kenya_output.csv")
#names to rename
levels_renaming = {
    "Elgeyo-Marakwet" : "Elgeyo Marakwet",
    "Tharaka-Nithi" : "Tharaka Nithi",
    }

kenya_hki["ADM1_EN"]=kenya_hki["ADM1_EN"].replace(levels_renaming)
kenya_hki.to_csv(input2_path / "clean_hki_kenya_output.csv")

In [8]:
nigeria_hki= pd.read_csv(input1_path/ "hki_nigeria_output.csv")
#names to rename
levels_renaming = {
    "Nasarawa" : "Nassarawa",
    }

nigeria_hki["ADM1_EN"]=nigeria_hki["ADM1_EN"].replace(levels_renaming)
nigeria_hki.to_csv(input2_path / "clean_hki_nigeria_output.csv")

In [9]:
drc_hki= pd.read_csv(input1_path/ "hki_drc_output.csv")
#names to rename
levels_renaming = {
    "Kasaï-Oriental" : "Kasai Oriental",
    "Kongo-Central" : "Kongo Central",
    }

drc_hki["ADM1_FR"]=drc_hki["ADM1_FR"].replace(levels_renaming)
drc_hki.to_csv(input2_path / "clean_hki_drc_output.csv")

In [10]:
mali_hki= pd.read_csv(input1_path/ "hki_mali_output.csv")
#names to rename
levels_renaming = {
    "Ségou" : "Segou",
    }

mali_hki["ADM1_FR"]=mali_hki["ADM1_FR"].replace(levels_renaming)
mali_hki.to_csv(input2_path / "clean_hki_mali_output.csv")

In [11]:
##Niger

niger_hki= pd.read_csv(input1_path/ "hki_niger_output.csv")
#names to rename
levels_renaming = {
    "Tillabéri" : "Tillaberi",
    }

niger_hki["adm_01"]=niger_hki["adm_01"].replace(levels_renaming)
niger_hki.to_csv(input2_path / "clean_hki_niger_output.csv")

In [12]:
# ### Cote'd'Ivoire

# cote_d_ivoire_hki= pd.read_csv(input1_path/ "hki_cote_d_ivoire_output.csv")
# #names to rename
# levels_renaming = {
#     "" : "Abobo-Est",
#     }

# cote_d_ivoire_hki["ADM1_FR"]=cote_d_ivoire_hki["ADM1_FR"].replace(levels_renaming)
# cote_d_ivoire_hki.to_csv(input2_path / "clean_hki_cote_d_ivoire_output.csv")

### Malaria Consortium countries

#### 1. Nigeria

Read outputs

In [13]:
nigeria_mc_output= pd.read_csv(input2_path/ "clean_mc_nigeria_output.csv")
nigeria_mc_output

,Unnamed: 0,ADM1_EN,ADM2_EN,worldpop_cons_u5_nga_f_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_nga_m_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,worldpop_wopr_u5_sum,worldpop_wopr_3-59_months,facebook_u5_sum,facebook_3-59_months
0,0,Bauchi,Alkaleri,37571,36599,74170,70461.50,81989,77889.55,88787,84347.65
1,1,Bauchi,Bauchi,59878,58328,118206,112295.70,258402,245481.90,133585,126905.75
2,2,Bauchi,Bogoro,13240,12898,26138,24831.10,27681,26296.95,28951,27503.45
3,3,Bauchi,Damban,21510,20953,42463,40339.85,40404,38383.80,52379,49760.05
4,4,Bauchi,Darazo,38443,37448,75891,72096.45,86984,82634.80,95062,90308.90
...,...,...,...,...,...,...,...,...,...,...,...
137,137,Sokoto,Tangaza,11827,11521,23348,22180.60,52305,49689.75,28585,27155.75
138,138,Sokoto,Tureta,13005,12668,25673,24389.35,30338,28821.10,33207,31546.65
139,139,Sokoto,Wamakko,20269,19744,40013,38012.35,107611,102230.45,44341,42123.95
140,140,Sokoto,Wurno,22237,21661,43898,41703.10,61184,58124.80,52893,50248.35
141,141,Sokoto,Yabo,10028,9768,19796,18806.20,40017,38016.15,23030,21878.50

Read charity provided estimates

In [14]:
nigeria_mc_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="MC Nigeria")

In [15]:
nigeria_mc_data=nigeria_mc_data[["State","LGA","Submitted MC Data for Target Population(3M-59M) in 2021"]]
nigeria_mc_data

,State,LGA,Submitted MC Data for Target Population(3M-59M) in 2021
0,Sokoto,Binji,28726
1,Sokoto,Bodinga,37757
2,Sokoto,Dange Shuni,65736
3,Sokoto,Gada,68675
4,Sokoto,Goronyo,27237
...,...,...,...
127,Kogi,Yagba East,43755.1
128,Kogi,Yagba West,42393.75
129,NaN,Total,NaN
130,NaN,NaN,NaN
131,NaN,Source:,MC 2021 SMC Target Population

Rename column names

In [16]:
nigeria_mc_output=nigeria_mc_output.rename(columns={"ADM1_EN":"State","ADM2_EN": "LGA"})

Use concat to combine

In [17]:
nigeria_mc_merged = pd.merge(nigeria_mc_data, nigeria_mc_output, on=["State", "LGA"], how="left")
nigeria_mc_merged

,State,LGA,Submitted MC Data for Target Population(3M-59M) in 2021,Unnamed: 0,worldpop_cons_u5_nga_f_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_nga_m_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,worldpop_wopr_u5_sum,worldpop_wopr_3-59_months,facebook_u5_sum,facebook_3-59_months
0,Sokoto,Binji,28726,119.0,12835.0,12503.0,25338.0,24071.10,25616.0,24335.20,31811.0,30220.45
1,Sokoto,Bodinga,37757,120.0,22227.0,21652.0,43879.0,41685.05,71473.0,67899.35,53444.0,50771.80
2,Sokoto,Dange Shuni,65736,121.0,34538.0,33644.0,68182.0,64772.90,94696.0,89961.20,82540.0,78413.00
3,Sokoto,Gada,68675,122.0,23957.0,23337.0,47294.0,44929.30,108757.0,103319.15,58363.0,55444.85
4,Sokoto,Goronyo,27237,123.0,23546.0,22936.0,46482.0,44157.90,57566.0,54687.70,61018.0,57967.10
...,...,...,...,...,...,...,...,...,...,...,...,...
127,Kogi,Yagba East,43755.1,87.0,15498.0,15097.0,30595.0,29065.25,17070.0,16216.50,35183.0,33423.85
128,Kogi,Yagba West,42393.75,88.0,17285.0,16838.0,34123.0,32416.85,10122.0,9615.90,35326.0,33559.70
129,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,Source:,MC 2021 SMC Target Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Calculate percentage differences

In [18]:
nigeria_mc_merged["cons_perc_difference"]=((nigeria_mc_merged["worldpop_cons_3-59_months"]- nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])/nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])
nigeria_mc_merged["wopr_perc_difference"]=((nigeria_mc_merged["worldpop_wopr_3-59_months"]- nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])/nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])
nigeria_mc_merged["meta_perc_difference"]=((nigeria_mc_merged["facebook_3-59_months"]- nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])/ nigeria_mc_merged["Submitted MC Data for Target Population(3M-59M) in 2021"])

Save to file

In [19]:
ordered_col_names=['State', 'LGA',
       'Submitted MC Data for Target Population(3M-59M) in 2021', 'worldpop_cons_3-59_months','cons_perc_difference',
       'worldpop_wopr_3-59_months', 'wopr_perc_difference', 'facebook_3-59_months',     'meta_perc_difference', ]

In [20]:
nigeria_mc_merged=nigeria_mc_merged[ordered_col_names]
nigeria_mc_merged

,State,LGA,Submitted MC Data for Target Population(3M-59M) in 2021,worldpop_cons_3-59_months,cons_perc_difference,worldpop_wopr_3-59_months,wopr_perc_difference,facebook_3-59_months,meta_perc_difference
0,Sokoto,Binji,28726,24071.10,-0.162045,24335.20,-0.152851,30220.45,0.052024
1,Sokoto,Bodinga,37757,41685.05,0.104035,67899.35,0.798325,50771.80,0.344699
2,Sokoto,Dange Shuni,65736,64772.90,-0.014651,89961.20,0.368523,78413.00,0.192847
3,Sokoto,Gada,68675,44929.30,-0.345769,103319.15,0.504465,55444.85,-0.192649
4,Sokoto,Goronyo,27237,44157.90,0.621247,54687.70,1.007846,57967.10,1.128248
...,...,...,...,...,...,...,...,...,...
127,Kogi,Yagba East,43755.1,29065.25,-0.335729,16216.50,-0.62938,33423.85,-0.236115
128,Kogi,Yagba West,42393.75,32416.85,-0.235339,9615.90,-0.773176,33559.70,-0.208381
129,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,Source:,MC 2021 SMC Target Population,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
nigeria_mc_merged.to_excel(writer, sheet_name= "MC_Nigeria",index=False)

#### 2. Chad

Read outputs

In [22]:
chad_mc_output= pd.read_csv(input2_path/ "clean_mc_chad_output.csv")
chad_mc_output

,Unnamed: 0.1,Unnamed: 0,District,RegName,geometry,worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,tcd_children_under_five_2020,facebook_3-59_months
0,0,0,9e Arrondissement,N'Djamena,POLYGON Z ((15.04868549500003 12.0863161520000...,25241,24519,49760,47272.00,41802.962255,39712.814142
1,1,1,Abdi,Ouaddai,POLYGON Z ((21.310583000000065 13.160848000000...,17831,17321,35152,33394.40,33135.095590,31478.340811
2,2,2,Abeche,Ouaddai,POLYGON Z ((21.14911900000004 14.0312490000000...,36934,35878,72812,69171.40,81262.264047,77199.150845
3,3,3,Aboudeia,Salamat,POLYGON Z ((19.751000000000033 12.053000000000...,8153,7920,16073,15269.35,17095.805218,16241.014957
4,4,4,Abougoudam,Ouaddai,POLYGON Z ((21.352293607000036 13.256151919000...,13362,12980,26342,25024.90,19101.363908,18146.295713
...,...,...,...,...,...,...,...,...,...,...,...
121,121,121,Tissi,Sila,POLYGON Z ((22.554689410000037 11.694129940000...,10859,10549,21408,20337.60,5035.680548,4783.896521
122,122,122,Torrock,Mayo Kebbi Ouest,POLYGON Z ((15.114499000000023 9.5977830000000...,6469,6284,12753,12115.35,8579.589284,8150.609820
123,123,123,Yao,Batha,POLYGON Z ((17.450000000000045 13.497000000000...,13673,13282,26955,25607.25,36068.029965,34264.628467
124,124,124,Youe,Mayo Kebbi Est,POLYGON Z ((14.96474900000004 9.71562900000003...,7750,7528,15278,14514.10,5883.994225,5589.794514
125,125,125,Zouar,Tibesti,MULTIPOLYGON Z (((18.764079000000038 21.408342...,2838,2756,5594,5314.30,971.858062,923.265159

Read charity provided estimates

In [23]:
chad_mc_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="MC Chad")

In [24]:
chad_mc_data=chad_mc_data[["Region","Health District","Submitted Malaria Consortium Data for Target Population in 2017"]]
chad_mc_data

,Region,Health District,Submitted Malaria Consortium Data for Target Population in 2017
0,Bahr el Ghazal,Chadra,20484
1,Bahr el Ghazal,Michemere,9893
2,Bahr el Ghazal,Moussoro,38734
3,Bahr el Ghazal,Salal,10612
4,Batha,Yao,23619
5,Chari Baguirmi,Ba-Illi,36304
6,Chari Baguirmi,Bousso,33795
7,Chari Baguirmi,Dourbali,38661
8,Chari Baguirmi,Mandelia,62937
9,Chari Baguirmi,Massenya,36364
10,Chari Baguirmi,Kouno,11834
11,Hadjer Lamis,Bokoro,58183
12,Hadjer Lamis,Gama,19942
13,Hadjer Lamis,Karal,28499
14,Hadjer Lamis,Mani,23173
15,Hadjer Lamis,Massaguet,43175
16,Hadjer Lamis,Massakory,30937
17,Mayo Kebbi Est,Bongor,52165
18,Mayo Kebbi Est,Gam*,20418
19,Mayo Kebbi Est,Guelendeng,33520
20,Mayo Kebbi Est,Moulkou**,26287
21,N'Djamena,N'Djamena Centre,92011
22,N'Djamena,N'Djamena Est,108632
23,N'Djamena,N'Djamena Nord,69939
24,N'Djamena,N'Djamena Sud,106101
25,N'Djamena,Toukra,44347

Rename column names

In [25]:
chad_mc_output=chad_mc_output.rename(columns={"District": "Health District",	"RegName" : "Region"})

Use concat to combine

In [26]:
chad_mc_merged=pd.merge(chad_mc_data,chad_mc_output,on=["Health District"])
chad_mc_merged.columns

Index(['Region_x', 'Health District',
       'Submitted Malaria Consortium Data for Target Population in 2017',
       'Unnamed: 0.1', 'Unnamed: 0', 'Region_y', 'geometry',
       'worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'tcd_children_under_five_2020', 'facebook_3-59_months'],
      dtype='object')

Calculate percentage differences

In [27]:
chad_mc_output.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Health District', 'Region', 'geometry',
       'worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'tcd_children_under_five_2020', 'facebook_3-59_months'],
      dtype='object')

In [28]:
chad_mc_merged["cons_perc_difference"]  =  ((chad_mc_merged["worldpop_cons_3-59_months"]  -   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])  /  chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])
# chad_mc_merged["wopr_perc_difference"]  =  ((chad_mc_merged["worldpop_wopr_3-59_months"]  -   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])  /  chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])
chad_mc_merged["meta_perc_difference"]  =  ((chad_mc_merged["facebook_3-59_months"]  -   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])  /   chad_mc_merged["Submitted Malaria Consortium Data for Target Population in 2017"])

Save to file

In [29]:
chad_mc_merged.columns

Index(['Region_x', 'Health District',
       'Submitted Malaria Consortium Data for Target Population in 2017',
       'Unnamed: 0.1', 'Unnamed: 0', 'Region_y', 'geometry',
       'worldpop_cons_u5_tcd_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_tcd_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'tcd_children_under_five_2020', 'facebook_3-59_months',
       'cons_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [30]:
ordered_col_names = [
    'Region_x', 
    'Health District',
    'Submitted Malaria Consortium Data for Target Population in 2017',
    'worldpop_cons_3-59_months',
    'cons_perc_difference',
    'facebook_3-59_months',
    'meta_perc_difference'
]

In [31]:
chad_mc_merged=chad_mc_merged[ordered_col_names]
chad_mc_merged

,Region_x,Health District,Submitted Malaria Consortium Data for Target Population in 2017,worldpop_cons_3-59_months,cons_perc_difference,facebook_3-59_months,meta_perc_difference
0,Bahr el Ghazal,Chadra,20484,19730.55,-0.036782,9754.000974,-0.523823
1,Bahr el Ghazal,Michemere,9893,14326.95,0.448191,7400.452971,-0.251951
2,Bahr el Ghazal,Moussoro,38734,24965.05,-0.355475,18157.754651,-0.531219
3,Bahr el Ghazal,Salal,10612,14591.05,0.374958,9933.624848,-0.063925
4,Batha,Yao,23619,25607.25,0.084180,34264.628467,0.450723
5,Chari Baguirmi,Ba-Illi,36304,16703.85,-0.539890,13565.317185,-0.626341
6,Chari Baguirmi,Bousso,33795,23779.45,-0.296362,20613.675398,-0.390038
7,Chari Baguirmi,Dourbali,38661,30780.00,-0.203849,30908.272043,-0.200531
8,Chari Baguirmi,Mandelia,62937,16892.90,-0.731590,12416.390493,-0.802717
9,Chari Baguirmi,Massenya,36364,21587.80,-0.406341,14120.190707,-0.611699
10,Chari Baguirmi,Kouno,11834,10893.65,-0.079462,7877.110233,-0.334366
11,Hadjer Lamis,Bokoro,58183,42039.40,-0.277462,35436.572461,-0.390946
12,Hadjer Lamis,Gama,19942,15557.20,-0.219878,12078.906625,-0.394298
13,Hadjer Lamis,Karal,28499,11461.75,-0.597819,8816.871976,-0.690625
14,Hadjer Lamis,Mani,23173,8934.75,-0.614433,8347.220198,-0.639787
15,Hadjer Lamis,Massaguet,43175,25882.75,-0.400515,18550.489307,-0.570342
16,Hadjer Lamis,Massakory,30937,27066.45,-0.125111,25018.238313,-0.191317
17,Mayo Kebbi Est,Bongor,52165,39944.65,-0.234263,46425.945558,-0.110017
18,Mayo Kebbi Est,Guelendeng,33520,17713.70,-0.471548,14164.909645,-0.577419
19,Mayo Kebbi Est,Moulkou**,26287,21625.80,-0.177320,11246.578656,-0.572162
20,N'Djamena,N'Djamena Centre,92011,34074.60,-0.629668,42580.760702,-0.537221
21,N'Djamena,N'Djamena Est,108632,52506.50,-0.516657,54102.953960,-0.501961
22,N'Djamena,N'Djamena Nord,69939,99268.35,0.419356,109916.442900,0.571604
23,N'Djamena,N'Djamena Sud,106101,58899.05,-0.444878,59161.855418,-0.442401

In [32]:
chad_mc_merged.to_excel(writer, sheet_name="MC_Chad", index=False)

#### 3. Burkina Faso

Read outputs

In [33]:
burkinafaso_mc_output= pd.read_csv(input2_path/ "clean_mc_burkinafaso_output.csv")
burkinafaso_mc_output["NOMDEP"]  =  burkinafaso_mc_output["NOMDEP"].str.title()
burkinafaso_mc_output

,Unnamed: 0,NOMDEP,NOMPROVINC,worldpop_cons_u5_bfa_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_bfa_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_3-59_months,worldpop_wopr_u5_sum,worldpop_wopr_3-59_months,facebook_u5_sum,facebook_3-59_months
0,0,Banfora,COMOE,37549,36316,73865,70171.75,59077,56123.15,75031,71279.45
1,1,Barsalogho,SANMATENGA,18256,17657,35913,34117.35,31616,30035.20,38951,37003.45
2,2,Baskuy,KADIOGO,26933,26049,52982,50332.90,29028,27576.60,27051,25698.45
3,3,Batie,NOUMBIEL,8707,8421,17128,16271.60,15994,15194.30,17293,16428.35
4,4,Bittou,BOULGOU,12538,12126,24664,23430.80,22875,21731.25,26964,25615.80
...,...,...,...,...,...,...,...,...,...,...,...
65,65,Tougouri,NAMENTENGA,20118,19457,39575,37596.25,45690,43405.50,43214,41053.30
66,66,Yako,PASSORE,33364,32269,65633,62351.35,74592,70862.40,67310,63944.50
67,67,Zabre,BOULGOU,11760,11374,23134,21977.30,27056,25703.20,24367,23148.65
68,68,Ziniaré,OUBRITENGA,25110,24285,49395,46925.25,53179,50520.05,51474,48900.30
69,69,Zorgho,GANZOURGOU,35256,34098,69354,65886.30,75427,71655.65,72064,68460.80

Read charity provided estimates

In [34]:
burkinafaso_mc_data  =  pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="MC Burkina Faso")

In [35]:
burkinafaso_mc_data=burkinafaso_mc_data[["Region","Health district","Submitted Malaria Consortium Data for Target Population in 2021"]]
burkinafaso_mc_data

,Region,Health district,Submitted Malaria Consortium Data for Target Population in 2021
0,Cascades,Banfora,72716
1,Cascades,Mangodara,70559
2,Cascades,Sindou,32455
3,Centre,Baskuy,42913
4,Centre,Bogodogo,193037
5,Centre,Boulmiougou,222474
6,Centre,Nongr-Massom,87565
7,Centre,Sig-Nonghin,104265
8,Centre-Nord,Barsalogho,47597
9,Centre-Nord,Boulsa,45052
10,Centre-Nord,Boussouma,44659
11,Centre-Nord,Kaya,101788
12,Centre-Nord,Koungoussi,89956
13,Centre-Nord,Tougouri,58087
14,Centre-Sud,Kombissiri,38540
15,Centre-Sud,Manga,64934
16,Centre-Sud,Pô,42141
17,Centre-Sud,Saponé,20597
18,Hauts Bassins,Dafra,85559
19,Hauts Bassins,Dandé,58497
20,Hauts Bassins,Dô,143149
21,Hauts Bassins,Houndé,57780
22,Hauts Bassins,Karangasso Vigué,22050
23,Hauts Bassins,Lena,15672
24,Hauts Bassins,N'Dorola,27704
25,Hauts Bassins,Orodara,45076
26,Plateau Central,Boussé,36311
27,Plateau Central,Ziniaré,63891
28,Plateau Central,Zorgho,86731

Rename column names

In [36]:
burkinafaso_mc_output=burkinafaso_mc_output.rename(columns={"NOMDEP" : "Health district",	"NOMPROVINC" : "Province"})

Use concat to combine

In [37]:
burkinafaso_mc_merged=pd.merge(burkinafaso_mc_data,burkinafaso_mc_output,on=["Health district"])
burkinafaso_mc_merged.columns

Index(['Region', 'Health district',
       'Submitted Malaria Consortium Data for Target Population in 2021',
       'Unnamed: 0', 'Province',
       'worldpop_cons_u5_bfa_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_bfa_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_3-59_months', 'facebook_u5_sum',
       'facebook_3-59_months'],
      dtype='object')

Calculate percentage differences

In [38]:
burkinafaso_mc_merged["cons_perc_difference"]  =  ((burkinafaso_mc_merged["worldpop_cons_3-59_months"]  -   burkinafaso_mc_merged["Submitted Malaria Consortium Data for Target Population in 2021"])  /  burkinafaso_mc_merged["Submitted Malaria Consortium Data for Target Population in 2021"])
burkinafaso_mc_merged["wopr_perc_difference"]  =  ((burkinafaso_mc_merged["worldpop_wopr_3-59_months"]  -   burkinafaso_mc_merged["Submitted Malaria Consortium Data for Target Population in 2021"])  /  burkinafaso_mc_merged["Submitted Malaria Consortium Data for Target Population in 2021"])
burkinafaso_mc_merged["meta_perc_difference"]  =  ((burkinafaso_mc_merged["facebook_3-59_months"]  -   burkinafaso_mc_merged["Submitted Malaria Consortium Data for Target Population in 2021"])  /   burkinafaso_mc_merged["Submitted Malaria Consortium Data for Target Population in 2021"])

Save to file

In [39]:
burkinafaso_mc_merged.columns

Index(['Region', 'Health district',
       'Submitted Malaria Consortium Data for Target Population in 2021',
       'Unnamed: 0', 'Province',
       'worldpop_cons_u5_bfa_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_bfa_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_3-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_3-59_months', 'facebook_u5_sum',
       'facebook_3-59_months', 'cons_perc_difference', 'wopr_perc_difference',
       'meta_perc_difference'],
      dtype='object')

In [40]:
ordered_col_names = [
    'Region', 
    'Province',
    'Health district',
    'Submitted Malaria Consortium Data for Target Population in 2021',
    'worldpop_cons_3-59_months',
    'cons_perc_difference',
    'worldpop_wopr_3-59_months', 
    'wopr_perc_difference',
    'facebook_3-59_months',
    'meta_perc_difference'
]

In [41]:
burkinafaso_mc_merged=burkinafaso_mc_merged[ordered_col_names]
burkinafaso_mc_merged

,Region,Province,Health district,Submitted Malaria Consortium Data for Target Population in 2021,worldpop_cons_3-59_months,cons_perc_difference,worldpop_wopr_3-59_months,wopr_perc_difference,facebook_3-59_months,meta_perc_difference
0,Cascades,COMOE,Banfora,72716,70171.75,-0.034989,56123.15,-0.228187,71279.45,-0.019756
1,Cascades,COMOE,Mangodara,70559,72197.15,0.023217,41593.85,-0.410510,74531.30,0.056298
2,Cascades,LERABA,Sindou,32455,28257.75,-0.129325,27565.20,-0.150664,29258.10,-0.098503
3,Centre,KADIOGO,Baskuy,42913,50332.90,0.172906,27576.60,-0.357384,25698.45,-0.401150
4,Centre,KADIOGO,Bogodogo,193037,182410.45,-0.055049,152560.50,-0.209683,130188.00,-0.325580
5,Centre,KADIOGO,Boulmiougou,222474,217219.40,-0.023619,154643.85,-0.304890,165618.25,-0.255561
6,Centre,KADIOGO,Nongr-Massom,87565,107128.65,0.223419,68869.30,-0.213507,79823.75,-0.088406
7,Centre,KADIOGO,Sig-Nonghin,104265,77290.10,-0.258715,60326.90,-0.421408,77654.90,-0.255216
8,Centre-Nord,SANMATENGA,Barsalogho,47597,34117.35,-0.283204,30035.20,-0.368969,37003.45,-0.222568
9,Centre-Nord,NAMENTENGA,Boulsa,45052,34202.85,-0.240814,35105.35,-0.220782,37173.50,-0.174876
10,Centre-Nord,SANMATENGA,Boussouma,44659,31774.65,-0.288505,32611.60,-0.269764,34219.95,-0.233750
11,Centre-Nord,SANMATENGA,Kaya,101788,63165.50,-0.379441,72822.25,-0.284569,68719.20,-0.324879
12,Centre-Nord,BAM,Koungoussi,89956,60149.25,-0.331348,73571.80,-0.182136,65336.25,-0.273687
13,Centre-Nord,NAMENTENGA,Tougouri,58087,37596.25,-0.352760,43405.50,-0.252750,41053.30,-0.293245
14,Centre-Sud,BAZEGA,Kombissiri,38540,28013.60,-0.273129,29584.90,-0.232359,28000.30,-0.273474
15,Centre-Sud,ZOUNDWEOGO,Manga,64934,50658.75,-0.219842,46356.20,-0.286103,50972.25,-0.215014
16,Centre-Sud,NAHOURI,Pô,42141,38656.45,-0.082688,29763.50,-0.293716,38231.80,-0.092765
17,Centre-Sud,BAZEGA,Saponé,20597,14505.55,-0.295745,14942.55,-0.274528,14463.75,-0.297774
18,Hauts Bassins,HOUET,Dafra,85559,84656.40,-0.010549,82807.70,-0.032157,79031.45,-0.076293
19,Hauts Bassins,HOUET,Dandé,58497,37942.05,-0.351385,36023.05,-0.384190,36948.35,-0.368372
20,Hauts Bassins,HOUET,Dô,143149,89484.30,-0.374887,84674.45,-0.408487,90980.55,-0.364435
21,Hauts Bassins,TUY,Houndé,57780,57095.95,-0.011839,50722.40,-0.122146,55737.45,-0.035350
22,Hauts Bassins,HOUET,Karangasso Vigué,22050,21724.60,-0.014757,18243.80,-0.172617,21120.40,-0.042159
23,Hauts Bassins,HOUET,Lena,15672,9409.75,-0.399582,11981.40,-0.235490,9111.45,-0.418616
24,Hauts Bassins,KENEDOUGOU,N'Dorola,27704,26869.80,-0.030111,23427.95,-0.154348,26309.30,-0.050343
25,Hauts Bassins,KENEDOUGOU,Orodara,45076,45757.70,0.015123,37646.60,-0.164819,44575.90,-0.011095
26,Plateau Central,KOURWEOGO,Boussé,36311,25971.10,-0.284759,27631.70,-0.239027,27010.40,-0.256137
27,Plateau Central,OUBRITENGA,Ziniaré,63891,46925.25,-0.265542,50520.05,-0.209278,48900.30,-0.234629
28,Plateau Central,GANZOURGOU,Zorgho,86731,65886.30,-0.240337,71655.65,-0.173817,68460.80,-0.210654

In [42]:
burkinafaso_mc_merged.to_excel(writer, sheet_name="MC_Burkina Faso", index=False)

### HKI Countries

#### Cameroon

Read outputs

In [43]:
cameroon_hki_output= pd.read_csv(input1_path/ "hki_cameroon_output.csv")
cameroon_hki_output

,ADM1_EN,ADM1_FR,worldpop_cons_u5_cmr_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_cmr_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,facebook_u5_sum,facebook_6-59_months
0,Adamawa,Adamaoua,115292,112938,228230,205407.0,252860,227574.0
1,Centre,Centre,455707,446404,902111,811899.9,849522,764569.8
2,East,Est,85111,83374,168485,151636.5,195168,175651.2
3,Far-North,Extrême-Nord,368902,361372,730274,657246.6,879753,791777.7
4,Littoral,Littoral,354574,347336,701910,631719.0,586270,527643.0
5,North,Nord,246272,241244,487516,438764.4,597805,538024.5
6,North-West,Nord-Ouest,185270,181488,366758,330082.2,334796,301316.4
7,South,Sud,76032,74480,150512,135460.8,161568,145411.2
8,South-West,Sud-Ouest,151328,148239,299567,269610.3,259754,233778.6
9,West,Ouest,169945,166476,336421,302778.9,338586,304727.4

Read charity provided estimates

In [44]:
cameroon_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Cameroon")
cameroon_hki_data

  Admin-Level1  Submitted HKI Data for Target Population in 2021(round 2)
0      Adamawa                                             346900
1       Centre                                             954481
2         East                                             283813
3     Littoral                                             543779
4         West                                             427963
5        South                                             119638
6   North-West                                             316093
7        North                                             753448
8   South-West                                             277503
9    Far-North                                            1359459

Rename column names

In [45]:
cameroon_hki_output=cameroon_hki_output.rename(columns={"ADM1_EN":"Admin-Level1"})
cameroon_hki_output

,Admin-Level1,ADM1_FR,worldpop_cons_u5_cmr_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_cmr_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,facebook_u5_sum,facebook_6-59_months
0,Adamawa,Adamaoua,115292,112938,228230,205407.0,252860,227574.0
1,Centre,Centre,455707,446404,902111,811899.9,849522,764569.8
2,East,Est,85111,83374,168485,151636.5,195168,175651.2
3,Far-North,Extrême-Nord,368902,361372,730274,657246.6,879753,791777.7
4,Littoral,Littoral,354574,347336,701910,631719.0,586270,527643.0
5,North,Nord,246272,241244,487516,438764.4,597805,538024.5
6,North-West,Nord-Ouest,185270,181488,366758,330082.2,334796,301316.4
7,South,Sud,76032,74480,150512,135460.8,161568,145411.2
8,South-West,Sud-Ouest,151328,148239,299567,269610.3,259754,233778.6
9,West,Ouest,169945,166476,336421,302778.9,338586,304727.4

Merge the files

In [46]:
cameroon_hki_merged=pd.merge( cameroon_hki_data, cameroon_hki_output, on=["Admin-Level1"])
cameroon_hki_merged.columns

Index(['Admin-Level1',
       'Submitted HKI Data for Target Population in 2021(round 2)', 'ADM1_FR',
       'worldpop_cons_u5_cmr_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_cmr_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'facebook_u5_sum', 'facebook_6-59_months'],
      dtype='object')

Calculate percentage differences

In [47]:
cameroon_hki_merged["cons_perc_difference"]   =   ((cameroon_hki_merged["worldpop_cons_6-59_months"]   -   cameroon_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])   /   cameroon_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])
cameroon_hki_merged["meta_perc_difference"]   =   ((cameroon_hki_merged["facebook_6-59_months"]   -   cameroon_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])   /   cameroon_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])

Save to file

In [48]:
cameroon_hki_merged.columns

Index(['Admin-Level1',
       'Submitted HKI Data for Target Population in 2021(round 2)', 'ADM1_FR',
       'worldpop_cons_u5_cmr_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_cmr_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'facebook_u5_sum', 'facebook_6-59_months', 'cons_perc_difference',
       'meta_perc_difference'],
      dtype='object')

In [49]:
ordered_col_names = [
    'Admin-Level1', 
    'Submitted HKI Data for Target Population in 2021(round 2)',
    'worldpop_cons_6-59_months',
    'cons_perc_difference',
    'facebook_6-59_months',
    'meta_perc_difference'
]

In [50]:
cameroon_hki_merged=cameroon_hki_merged[ordered_col_names]
cameroon_hki_merged

,Admin-Level1,Submitted HKI Data for Target Population in 2021(round 2),worldpop_cons_6-59_months,cons_perc_difference,facebook_6-59_months,meta_perc_difference
0,Adamawa,346900,205407.0,-0.407878,227574.0,-0.343978
1,Centre,954481,811899.9,-0.149381,764569.8,-0.198968
2,East,283813,151636.5,-0.465717,175651.2,-0.381102
3,Littoral,543779,631719.0,0.161720,527643.0,-0.029674
4,West,427963,302778.9,-0.292512,304727.4,-0.287959
5,South,119638,135460.8,0.132256,145411.2,0.215427
6,North-West,316093,330082.2,0.044257,301316.4,-0.046748
7,North,753448,438764.4,-0.417658,538024.5,-0.285917
8,South-West,277503,269610.3,-0.028442,233778.6,-0.157564
9,Far-North,1359459,657246.6,-0.516538,791777.7,-0.417579

In [51]:
cameroon_hki_merged.to_excel(writer, sheet_name="HKI_Cameroon", index=False)

#### Kenya

Read outputs

In [52]:
kenya_hki_output= pd.read_csv(input2_path/ "clean_hki_kenya_output.csv")
kenya_hki_output

,Unnamed: 0,ADM1_EN,worldpop_cons_u5_ken_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_ken_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,facebook_u5_sum,facebook_6-59_months
0,0,Baringo,51210,50524,101734,91560.6,54049,48644.1,130223,117200.7
1,1,Bomet,69331,68403,137734,123960.6,64105,57694.5,172412,155170.8
2,2,Bungoma,114581,113047,227628,204865.2,126074,113466.6,340627,306564.3
3,3,Busia,62040,61209,123249,110924.1,65403,58862.7,177669,159902.1
4,4,Elgeyo Marakwet,35217,34745,69962,62965.8,34249,30824.1,90235,81211.5
5,5,Embu,41380,40826,82206,73985.4,35138,31624.2,121541,109386.9
6,6,Garissa,98841,97518,196359,176723.1,76280,68652.0,169324,152391.6
7,7,Homa Bay,76787,75759,152546,137291.4,87658,78892.2,213971,192573.9
8,8,Isiolo,12242,12078,24320,21888.0,25415,22873.5,56221,50598.9
9,9,Kajiado,63209,62363,125572,113014.8,93676,84308.4,210258,189232.2
10,10,Kakamega,140171,138295,278466,250619.4,128388,115549.2,366499,329849.1
11,11,Kericho,71096,70144,141240,127116.0,62397,56157.3,177973,160175.7
12,12,Kiambu,121648,120019,241667,217500.3,163520,147168.0,496594,446934.6
13,13,Kilifi,96067,94781,190848,171763.2,115793,104213.7,287496,258746.4
14,14,Kirinyaga,40085,39549,79634,71670.6,32457,29211.3,117580,105822.0
15,15,Kisii,92385,91148,183533,165179.7,81768,73591.2,247469,222722.1
16,16,Kisumu,78606,77554,156160,140544.0,82116,73904.4,220181,198162.9
17,17,Kitui,80793,79711,160504,144453.6,71874,64686.6,206188,185569.2
18,18,Kwale,53656,52938,106594,95934.6,75547,67992.3,166380,149742.0
19,19,Laikipia,37766,37260,75026,67523.4,38395,34555.5,103835,93451.5
20,20,Lamu,6647,6558,13205,11884.5,10330,9297.0,26756,24080.4
21,21,Machakos,87027,85862,172889,155600.1,86214,77592.6,275071,247563.9
22,22,Makueni,71118,70166,141284,127155.6,55381,49842.9,190709,171638.1
23,23,Mandera,169657,167385,337042,303337.8,93689,84320.1,167366,150629.4
24,24,Marsabit,22997,22689,45686,41117.4,39794,35814.6,90712,81640.8
25,25,Meru,108632,107178,215810,194229.0,97197,87477.3,306136,275522.4
26,26,Migori,70452,69509,139961,125964.9,94635,85171.5,220275,198247.5
27,27,Mombasa,78070,77025,155095,139585.5,84346,75911.4,224738,202264.2
28,28,Murang'a,71615,70657,142272,128044.8,62348,56113.2,199092,179182.8
29,29,Nairobi,305226,301140,606366,545729.4,312138,280924.2,911619,820457.1
30,30,Nakuru,151019,148997,300016,270014.4,159798,143818.2,358666,322799.4
31,31,Nandi,71473,70516,141989,127790.1,60879,54791.1,163634,147270.6
32,32,Narok,80886,79803,160689,144620.1,111016,99914.4,260207,234186.3
33,33,Nyamira,48503,47853,96356,86720.4,35773,32195.7,122539,110285.1
34,34,Nyandarua,45845,45231,91076,81968.4,39187,35268.3,123315,110983.5
35,35,Nyeri,52416,51715,104131,93717.9,41046,36941.4,141783,127604.7
36,36,Samburu,20877,20598,41475,37327.5,30366,27329.4,67489,60740.1
37,37,Siaya,68273,67359,135632,122068.8,71076,63968.4,178513,160661.7
38,38,Taita Taveta,24815,24483,49298,44368.2,22786,20507.4,65517,58965.3
39,39,Tana River,25254,24916,50170,45153.0,35508,31957.2,68516,61664.4
40,40,Tharaka Nithi,27987,27612,55599,50039.1,22201,19980.9,69242,62317.8
41,41,Trans Nzoia,76663,75637,152300,137070.0,74530,67077.0,188534,169680.6
42,42,Turkana,78823,77768,156591,140931.9,75766,68189.4,135102,121591.8
43,43,Uasin Gishu,85142,84003,169145,152230.5,81130,73017.0,220929,198836.1
44,44,Vihiga,46275,45655,91930,82737.0,36091,32481.9,101983,91784.7
45,45,Wajir,109591,108124,217715,195943.5,70902,63811.8,148416,133574.4
46,46,West Pokot,47625,46987,94612,85150.8,65898,59308.2,134217,120795.3

Read charity provided estimates

In [53]:
kenya_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Kenya")

In [54]:
kenya_hki_data=kenya_hki_data[["Admin_level1","Submitted HKI Data for Target Population in 2021(Round 1 and 2)"]]
kenya_hki_data

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round 1 and 2)
0,Bungoma,205402
1,Elgeyo Marakwet,57162
2,Kakamega,209286
3,Kilifi,189076
4,Kirinyaga,53336
5,Kwale,123461
6,Siaya,120735
7,Taita Taveta,36158
8,Tharaka Nithi,36913
9,Trans Nzoia,122391
10,Uasin Gishu,130845
11,Bomet,104059
12,Busia,106203
13,Embu,56991
14,Kajiado,148883
15,Kiambu,261260
16,Makueni,88979
17,Muranga,103122
18,Nakuru,256871
19,Nandi,99348
20,Vihiga,74603
21,Baringo,90186
22,Garissa,155993
23,Homa Bay,145826
24,Isiolo,38160
25,Kericho,102970
26,Kisii,150946
27,Kisumu,166691
28,Kitui,116662
29,Laikipia,68615
30,Lamu,17461
31,Machakos,137377
32,Mandera,157591
33,Marsabit,64612
34,Meru,158868
35,Migori,160356
36,Mombasa,136172
37,Nairobi,486131
38,Narok,179668
39,Nyamira,93693
40,Samburu,48567
41,Tana River,58270
42,Turkana,121638
43,Wajir,117219
44,West Pokot,112879
45,Nyandarua,65164
46,Nyeri,66302

Rename column names

In [55]:
kenya_hki_output=kenya_hki_output.rename(columns={"ADM1_EN":"Admin_level1"})

Use concat to combine

In [56]:
kenya_hki_merged  =  pd.merge(kenya_hki_output, kenya_hki_data,  on=["Admin_level1"])

Calculate percentage differences

In [57]:
kenya_hki_merged["cons_perc_difference"]  =  ((kenya_hki_merged["worldpop_cons_6-59_months"]  -  kenya_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])  /  kenya_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])
kenya_hki_merged["wopr_perc_difference"]  =  ((kenya_hki_merged["worldpop_wopr_6-59_months"]  -  kenya_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])  /  kenya_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])
kenya_hki_merged["meta_perc_difference"]  =  ((kenya_hki_merged["facebook_6-59_months"]  -  kenya_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])  /   kenya_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])

Save to file

In [58]:
kenya_hki_merged.columns

Index(['Unnamed: 0', 'Admin_level1',
       'worldpop_cons_u5_ken_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_ken_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months', 'facebook_u5_sum',
       'facebook_6-59_months',
       'Submitted HKI Data for Target Population in 2021(Round 1 and 2)',
       'cons_perc_difference', 'wopr_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [59]:
ordered_col_names  =  ['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round 1 and 2)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',
       'worldpop_wopr_6-59_months',
       'wopr_perc_difference',
       'facebook_6-59_months',  
       'meta_perc_difference'
         ]

In [60]:
kenya_hki_merged  =  kenya_hki_merged[ordered_col_names]
kenya_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round 1 and 2),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Baringo,90186,91560.6,0.015242,48644.1,-0.460625,117200.7,0.299544
1,Bomet,104059,123960.6,0.191253,57694.5,-0.445560,155170.8,0.491181
2,Bungoma,205402,204865.2,-0.002613,113466.6,-0.447588,306564.3,0.492509
3,Busia,106203,110924.1,0.044454,58862.7,-0.445753,159902.1,0.505627
4,Elgeyo Marakwet,57162,62965.8,0.101532,30824.1,-0.460759,81211.5,0.420725
5,Embu,56991,73985.4,0.298194,31624.2,-0.445102,109386.9,0.919371
6,Garissa,155993,176723.1,0.132891,68652.0,-0.559903,152391.6,-0.023087
7,Homa Bay,145826,137291.4,-0.058526,78892.2,-0.458998,192573.9,0.320573
8,Isiolo,38160,21888.0,-0.426415,22873.5,-0.400590,50598.9,0.325967
9,Kajiado,148883,113014.8,-0.240915,84308.4,-0.433727,189232.2,0.271013
10,Kakamega,209286,250619.4,0.197497,115549.2,-0.447889,329849.1,0.576069
11,Kericho,102970,127116.0,0.234495,56157.3,-0.454625,160175.7,0.555557
12,Kiambu,261260,217500.3,-0.167495,147168.0,-0.436699,446934.6,0.710689
13,Kilifi,189076,171763.2,-0.091565,104213.7,-0.448826,258746.4,0.368478
14,Kirinyaga,53336,71670.6,0.343757,29211.3,-0.452316,105822.0,0.984063
15,Kisii,150946,165179.7,0.094297,73591.2,-0.512467,222722.1,0.475508
16,Kisumu,166691,140544.0,-0.156859,73904.4,-0.556638,198162.9,0.188804
17,Kitui,116662,144453.6,0.238223,64686.6,-0.445521,185569.2,0.590657
18,Kwale,123461,95934.6,-0.222956,67992.3,-0.449281,149742.0,0.212869
19,Laikipia,68615,67523.4,-0.015909,34555.5,-0.496386,93451.5,0.361969
20,Lamu,17461,11884.5,-0.319369,9297.0,-0.467556,24080.4,0.379096
21,Machakos,137377,155600.1,0.132650,77592.6,-0.435185,247563.9,0.802077
22,Makueni,88979,127155.6,0.429052,49842.9,-0.439835,171638.1,0.928973
23,Mandera,157591,303337.8,0.924842,84320.1,-0.464943,150629.4,-0.044175
24,Marsabit,64612,41117.4,-0.363626,35814.6,-0.445697,81640.8,0.263555
25,Meru,158868,194229.0,0.222581,87477.3,-0.449371,275522.4,0.734285
26,Migori,160356,125964.9,-0.214467,85171.5,-0.468860,198247.5,0.236296
27,Mombasa,136172,139585.5,0.025068,75911.4,-0.442533,202264.2,0.485358
28,Nairobi,486131,545729.4,0.122597,280924.2,-0.422122,820457.1,0.687728
29,Nakuru,256871,270014.4,0.051167,143818.2,-0.440115,322799.4,0.256660
30,Nandi,99348,127790.1,0.286288,54791.1,-0.448493,147270.6,0.482371
31,Narok,179668,144620.1,-0.195070,99914.4,-0.443894,234186.3,0.303439
32,Nyamira,93693,86720.4,-0.074420,32195.7,-0.656370,110285.1,0.177090
33,Nyandarua,65164,81968.4,0.257879,35268.3,-0.458776,110983.5,0.703141
34,Nyeri,66302,93717.9,0.413500,36941.4,-0.442831,127604.7,0.924598
35,Samburu,48567,37327.5,-0.231423,27329.4,-0.437285,60740.1,0.250646
36,Siaya,120735,122068.8,0.011047,63968.4,-0.470175,160661.7,0.330697
37,Taita Taveta,36158,44368.2,0.227065,20507.4,-0.432839,58965.3,0.630768
38,Tana River,58270,45153.0,-0.225107,31957.2,-0.451567,61664.4,0.058253
39,Tharaka Nithi,36913,50039.1,0.355596,19980.9,-0.458703,62317.8,0.688234
40,Trans Nzoia,122391,137070.0,0.119935,67077.0,-0.451945,169680.6,0.386381
41,Turkana,121638,140931.9,0.158617,68189.4,-0.439407,121591.8,-0.000380
42,Uasin Gishu,130845,152230.5,0.163441,73017.0,-0.441958,198836.1,0.519631
43,Vihiga,74603,82737.0,0.109030,32481.9,-0.564603,91784.7,0.230308
44,Wajir,117219,195943.5,0.671602,63811.8,-0.455619,133574.4,0.139529
45,West Pokot,112879,85150.8,-0.245645,59308.2,-0.474586,120795.3,0.070131

In [61]:
kenya_hki_merged.to_excel(writer ,sheet_name="HKI_Kenya",index=False)

#### Guinea

Read outputs

In [62]:
guinea_hki_output= pd.read_csv(input1_path/ "hki_guinea_output.csv")
guinea_hki_output

,admin1Name,worldpop_cons_u5_gin_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_gin_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,facebook_u5_sum,facebook_6-59_months
0,Boke,106702,103156,209858,188872.2,207375,186637.5,231450,208305.0
1,Conakry,164655,159182,323837,291453.3,236372,212734.8,352411,317169.9
2,Faranah,95038,91879,186917,168225.3,189896,170906.4,205921,185328.9
3,Kankan,218957,211679,430636,387572.4,468403,421562.7,475634,428070.6
4,Kindia,180406,174409,354815,319333.5,309430,278487.0,396068,356461.2
5,Labe,93669,90556,184225,165802.5,189278,170350.2,202602,182341.8
6,Mamou,67738,65486,133224,119901.6,137631,123867.9,146444,131799.6
7,Nzerekore,148197,143272,291469,262322.1,292823,263540.7,323272,290944.8

Read charity provided estimates

In [63]:
guinea_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Guinea")
guinea_hki_data

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round 1),Submitted HKI Data for Target Population in 2021(Round2),Population according to WorldPop Demographic database 2021,Percentage difference,Population according to WorldPop Top Down Constrained model,Percentage difference.1,Population according to Facebook HRSL,Percentage difference.2,Population according to WorldPop Bottom-Up,Percentage difference.3,Average across all alternative estimates,Percentage difference.4
0,Conakry,448854,493740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Boke,248816,285070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mamou,170395,187434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nzerekore,366812,403493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Faranah,224702,247172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Kankan,444212,488633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Kindia,461088,500892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Labe,227420,250162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
guinea_hki_data=guinea_hki_data[["Admin_level1","Submitted HKI Data for Target Population in 2021(Round2)", "Submitted HKI Data for Target Population in 2021(Round 1)"]]
guinea_hki_data

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round2),Submitted HKI Data for Target Population in 2021(Round 1)
0,Conakry,493740,448854
1,Boke,285070,248816
2,Mamou,187434,170395
3,Nzerekore,403493,366812
4,Faranah,247172,224702
5,Kankan,488633,444212
6,Kindia,500892,461088
7,Labe,250162,227420

Rename column names

In [65]:
guinea_hki_output=guinea_hki_output.rename(columns={"admin1Name":"Admin_level1"})

Use concat to combine

In [66]:
guinea_hki_merged=pd.merge(guinea_hki_data,guinea_hki_output,on="Admin_level1")

Calculate percentage differences

In [67]:
guinea_hki_merged["cons_perc_difference"]  =  ((guinea_hki_merged["worldpop_cons_6-59_months"]  -  guinea_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  guinea_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])
guinea_hki_merged["wopr_perc_difference"]  =  ((guinea_hki_merged["worldpop_wopr_6-59_months"]  -  guinea_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  / guinea_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])
guinea_hki_merged["meta_perc_difference"]  =  ((guinea_hki_merged["facebook_6-59_months"]  -  guinea_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  guinea_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])

Save to file

In [68]:
guinea_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'Submitted HKI Data for Target Population in 2021(Round 1)',
       'worldpop_cons_u5_gin_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_gin_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months', 'facebook_u5_sum',
       'facebook_6-59_months', 'cons_perc_difference', 'wopr_perc_difference',
       'meta_perc_difference'],
      dtype='object')

In [69]:
ordered_col_names=[
        'Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'Submitted HKI Data for Target Population in 2021(Round 1)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'worldpop_wopr_6-59_months', 
       'wopr_perc_difference',
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [70]:
guinea_hki_merged=guinea_hki_merged[ordered_col_names]
guinea_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round2),Submitted HKI Data for Target Population in 2021(Round 1),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Conakry,493740,448854,291453.3,-0.409703,212734.8,-0.569136,317169.9,-0.357618
1,Boke,285070,248816,188872.2,-0.337453,186637.5,-0.345292,208305.0,-0.269285
2,Mamou,187434,170395,119901.6,-0.360300,123867.9,-0.339139,131799.6,-0.296821
3,Nzerekore,403493,366812,262322.1,-0.349872,263540.7,-0.346852,290944.8,-0.278935
4,Faranah,247172,224702,168225.3,-0.319400,170906.4,-0.308553,185328.9,-0.250203
5,Kankan,488633,444212,387572.4,-0.206823,421562.7,-0.137261,428070.6,-0.123943
6,Kindia,500892,461088,319333.5,-0.362470,278487.0,-0.444018,356461.2,-0.288347
7,Labe,250162,227420,165802.5,-0.337219,170350.2,-0.319040,182341.8,-0.271105

In [71]:
guinea_hki_merged.to_excel(writer ,sheet_name="HKI_Guinea",index=False)

####  Nigeria

Read outputs

In [72]:
nigeria_hki_output= pd.read_csv(input2_path/ "clean_hki_nigeria_output.csv")
nigeria_hki_output

,Unnamed: 0,ADM1_EN,worldpop_cons_u5_nga_f_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_nga_m_0_4_2021_1km_UNadj_constrained_Nigeria_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,facebook_u5_sum,facebook_6-59_months
0,0,Abia,342079,333225,675304,607773.6,395110,375354.50,461286,415157.4
1,1,Adamawa,403581,393136,796717,717045.3,887359,842991.05,850174,765156.6
2,2,Akwa Ibom,508128,494977,1003105,902794.5,395105,375349.75,730008,657007.2
3,3,Anambra,489636,476964,966600,869940.0,566255,537942.25,643525,579172.5
4,4,Bauchi,595045,579645,1174690,1057221.0,1664629,1581397.55,1380317,1242285.3
5,5,Bayelsa,211898,206414,418312,376480.8,131802,125211.90,309272,278344.8
6,6,Benue,522959,509424,1032383,929144.7,1864954,1771706.30,1131589,1018430.1
7,7,Borno,536336,522455,1058791,952911.9,1130981,1074431.95,1202513,1082261.7
8,8,Cross River,313286,305177,618463,556616.7,263612,250431.40,477778,430000.2
9,9,Delta,516472,503105,1019577,917619.3,505036,479784.20,769238,692314.2
10,10,Ebonyi,273450,266372,539822,485839.8,481658,457575.10,478985,431086.5
11,11,Edo,386079,376087,762166,685949.4,492657,468024.15,565700,509130.0
12,12,Ekiti,300339,292566,592905,533614.5,186092,176787.40,403236,362912.4
13,13,Enugu,392349,382195,774544,697089.6,517831,491939.45,535624,482061.6
14,14,Federal Capital Territory,391851,381710,773561,696204.9,703645,668462.75,715788,644209.2
15,15,Gombe,285149,277769,562918,506626.2,816277,775463.15,656445,590800.5
16,16,Imo,494842,482035,976877,879189.3,673664,639980.80,685546,616991.4
17,17,Jigawa,503357,490330,993687,894318.3,1242576,1180447.20,1187044,1068339.6
18,18,Kaduna,754088,734572,1488660,1339794.0,2087890,1983495.50,1693722,1524349.8
19,19,Kano,1199062,1168029,2367091,2130381.9,3456570,3283741.50,2706011,2435409.9
20,20,Katsina,709265,690908,1400173,1260155.7,1967470,1869096.50,1740434,1566390.6
21,21,Kebbi,399331,388996,788327,709494.3,1105837,1050545.15,953456,858110.4
22,22,Kogi,388609,378551,767160,690444.0,699096,664141.20,868285,781456.5
23,23,Kwara,284269,276912,561181,505062.9,837529,795652.55,576543,518888.7
24,24,Lagos,1090491,1062268,2152759,1937483.1,1241865,1179771.75,1593619,1434257.1
25,25,Nassarawa,228251,222343,450594,405534.6,908003,862602.85,507179,456461.1
26,26,Niger,517090,503708,1020798,918718.2,2078880,1974936.00,1205598,1085038.2
27,27,Ogun,528516,514837,1043353,939017.7,1127318,1070952.10,888178,799360.2
28,28,Ondo,429222,418113,847335,762601.5,426975,405626.25,639874,575886.6
29,29,Osun,418219,407395,825614,743052.6,553077,525423.15,584510,526059.0
30,30,Oyo,710121,691742,1401863,1261676.7,881771,837682.45,1063579,957221.1
31,31,Plateau,385871,375884,761755,685579.5,1208717,1148281.15,774300,696870.0
32,32,Rivers,662475,645329,1307804,1177023.6,610684,580149.80,925719,833147.1
33,33,Sokoto,464328,452311,916639,824975.1,1454137,1381430.15,1091162,982045.8
34,34,Taraba,264325,257484,521809,469628.1,1094664,1039930.80,568442,511597.8
35,35,Yobe,304575,296692,601267,541140.3,913503,867827.85,677211,609489.9
36,36,Zamfara,402982,392553,795535,715981.5,1016241,965428.95,948742,853867.8

Read charity provided estimates

In [73]:
nigeria_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Nigeria")

In [74]:
nigeria_hki_data=nigeria_hki_data[["Admin_level1","Submitted HKI Data for Target Population in 2021(Round 1 & 2)"]]
nigeria_hki_data

   Admin_level1  Submitted HKI Data for Target Population in 2021(Round 1 & 2)
0          Abia                                             738806
1       Adamawa                                             875593
2     Nassarawa                                            1136577
3         Benue                                            1183220
4     Akwa Ibom                                            1165171
5       Anambra                                            1090229
6        Bauchi                                            1219103
7       Bayelsa                                             423905
8         Borno                                            1082190
9   Cross River                                             753135
10        Delta                                            1068425
11       Ebonyi                                             566618
12          Edo                                             838999
13        Ekiti                                             678249
14        Enugu                                             849157
15        Gombe                                             613641
16          Imo                                            1025803
17       Jigawa                                            1133665
18       Kaduna                                            1581514
19         Kano                                            2446266
20      Katsina                                            1510088
21        Kebbi                                             844290
22         Kogi                                             854681
23        Kwara                                             618128
24        Lagos                                            2349770
25        Niger                                            1029805
26         Ogun                                             971892
27         Ondo                                             897053
28         Osun                                             892494
29          Oyo                                            1457692
30      Plateau                                             828670
31       Rivers                                            1351801
32       Sokoto                                             963784
33       Taraba                                             630275
34         Yobe                                             605224
35      Zamfara                                             849821

Rename column names

In [75]:
nigeria_hki_output=nigeria_hki_output.rename(columns={"ADM1_EN":"Admin_level1"})

Use concat to combine

In [76]:
nigeria_hki_merged=pd.merge(nigeria_hki_data,nigeria_hki_output,on=["Admin_level1"])

Calculate percentage differences

In [77]:
nigeria_hki_merged["cons_perc_difference"]  = ((nigeria_hki_merged["worldpop_cons_6-59_months"]  - nigeria_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 & 2)"])  /  nigeria_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 & 2)"])
nigeria_hki_merged["wopr_perc_difference"]  = ((nigeria_hki_merged["worldpop_wopr_6-59_months"]  -  nigeria_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 & 2)"])  /  nigeria_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 & 2)"])
nigeria_hki_merged["meta_perc_difference"]  = ((nigeria_hki_merged["facebook_6-59_months"]  - nigeria_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 & 2)"])  /  nigeria_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 & 2)"])

Save to file

In [78]:
nigeria_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round 1 & 2)',
       'Unnamed: 0',
       'worldpop_cons_u5_nga_f_0_4_2021_1km_UNadj_constrained_Nigeria_sum',
       'worldpop_cons_u5_nga_m_0_4_2021_1km_UNadj_constrained_Nigeria_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months', 'facebook_u5_sum',
       'facebook_6-59_months', 'cons_perc_difference', 'wopr_perc_difference',
       'meta_perc_difference'],
      dtype='object')

In [79]:
ordered_col_names=[
        'Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round 1 & 2)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'worldpop_wopr_6-59_months', 
       'wopr_perc_difference',
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [80]:
nigeria_hki_merged=nigeria_hki_merged[ordered_col_names]
nigeria_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round 1 & 2),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Abia,738806,607773.6,-0.177357,375354.50,-0.491944,415157.4,-0.438070
1,Adamawa,875593,717045.3,-0.181075,842991.05,-0.037234,765156.6,-0.126128
2,Nassarawa,1136577,405534.6,-0.643197,862602.85,-0.241052,456461.1,-0.598390
3,Benue,1183220,929144.7,-0.214732,1771706.30,0.497360,1018430.1,-0.139272
4,Akwa Ibom,1165171,902794.5,-0.225183,375349.75,-0.677859,657007.2,-0.436128
5,Anambra,1090229,869940.0,-0.202058,537942.25,-0.506579,579172.5,-0.468761
6,Bauchi,1219103,1057221.0,-0.132788,1581397.55,0.297181,1242285.3,0.019016
7,Bayelsa,423905,376480.8,-0.111875,125211.90,-0.704623,278344.8,-0.343379
8,Borno,1082190,952911.9,-0.119460,1074431.95,-0.007169,1082261.7,0.000066
9,Cross River,753135,556616.7,-0.260934,250431.40,-0.667481,430000.2,-0.429053
10,Delta,1068425,917619.3,-0.141148,479784.20,-0.550943,692314.2,-0.352024
11,Ebonyi,566618,485839.8,-0.142562,457575.10,-0.192445,431086.5,-0.239194
12,Edo,838999,685949.4,-0.182419,468024.15,-0.442164,509130.0,-0.393170
13,Ekiti,678249,533614.5,-0.213247,176787.40,-0.739347,362912.4,-0.464927
14,Enugu,849157,697089.6,-0.179080,491939.45,-0.420673,482061.6,-0.432306
15,Gombe,613641,506626.2,-0.174393,775463.15,0.263708,590800.5,-0.037221
16,Imo,1025803,879189.3,-0.142926,639980.80,-0.376117,616991.4,-0.398528
17,Jigawa,1133665,894318.3,-0.211126,1180447.20,0.041266,1068339.6,-0.057623
18,Kaduna,1581514,1339794.0,-0.152841,1983495.50,0.254175,1524349.8,-0.036145
19,Kano,2446266,2130381.9,-0.129129,3283741.50,0.342349,2435409.9,-0.004438
20,Katsina,1510088,1260155.7,-0.165508,1869096.50,0.237740,1566390.6,0.037284
21,Kebbi,844290,709494.3,-0.159656,1050545.15,0.244294,858110.4,0.016369
22,Kogi,854681,690444.0,-0.192162,664141.20,-0.222937,781456.5,-0.085675
23,Kwara,618128,505062.9,-0.182915,795652.55,0.287197,518888.7,-0.160548
24,Lagos,2349770,1937483.1,-0.175458,1179771.75,-0.497920,1434257.1,-0.389618
25,Niger,1029805,918718.2,-0.107872,1974936.00,0.917777,1085038.2,0.053635
26,Ogun,971892,939017.7,-0.033825,1070952.10,0.101925,799360.2,-0.177522
27,Ondo,897053,762601.5,-0.149881,405626.25,-0.547824,575886.6,-0.358024
28,Osun,892494,743052.6,-0.167442,525423.15,-0.411287,526059.0,-0.410574
29,Oyo,1457692,1261676.7,-0.134470,837682.45,-0.425336,957221.1,-0.343331
30,Plateau,828670,685579.5,-0.172675,1148281.15,0.385692,696870.0,-0.159050
31,Rivers,1351801,1177023.6,-0.129292,580149.80,-0.570832,833147.1,-0.383676
32,Sokoto,963784,824975.1,-0.144025,1381430.15,0.433340,982045.8,0.018948
33,Taraba,630275,469628.1,-0.254884,1039930.80,0.649964,511597.8,-0.188294
34,Yobe,605224,541140.3,-0.105884,867827.85,0.433895,609489.9,0.007048
35,Zamfara,849821,715981.5,-0.157491,965428.95,0.136038,853867.8,0.004762

In [81]:
nigeria_hki_merged.to_excel(writer ,sheet_name="HKI_Nigeria",index=False)

####  DRC

Read outputs

In [82]:
drc_hki_output= pd.read_csv(input2_path/ "clean_hki_drc_output.csv")
drc_hki_output

,Unnamed: 0.1,Unnamed: 0,ADM1_FR,geometry,worldpop_cons_u5_cod_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_cod_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,cod_children_under_five_2020,facebook_6-59_months
0,0,0,Bas-Uele,POLYGON ((25.555046574000073 5.376462921000041...,121099,119901,241000,216900.0,0,0.00,2.137569e+05,1.923813e+05
1,1,1,Equateur,POLYGON ((19.511884588000044 2.021958127000061...,191777,189881,381658,343492.2,0,0.00,3.450817e+05,3.105736e+05
2,2,2,Haut-Katanga,POLYGON ((28.548101160000044 -7.62268462799994...,851558,843136,1694694,1525224.6,677938,644041.10,1.517221e+06,1.365499e+06
3,3,3,Haut-Lomami,POLYGON ((25.94889648000003 -6.234092813999950...,638477,632162,1270639,1143575.1,468906,445460.70,1.123740e+06,1.011366e+06
4,4,4,Haut-Uele,POLYGON ((27.394130326000038 5.096104767000043...,169691,168013,337704,303933.6,2069,1965.55,2.984763e+05,2.686286e+05
5,5,5,Ituri,"POLYGON ((30.78595522100005 3.64699902600006, ...",498602,493671,992273,893045.7,704099,668894.05,8.779015e+05,7.901114e+05
6,6,6,Kasaï,"POLYGON ((21.75535044000003 -2.49127901199995,...",503997,499012,1003009,902708.1,462616,439485.20,8.886901e+05,7.998211e+05
7,7,7,Kasaï-Central,POLYGON ((22.919164548000026 -4.52640419999994...,577854,572139,1149993,1034993.7,3509,3333.55,1.016891e+06,9.152021e+05
8,8,8,Kasai Oriental,POLYGON ((23.73511230400004 -5.689228568999965...,454947,450447,905394,814854.6,326358,310040.10,7.993290e+05,7.193961e+05
9,9,9,Kinshasa,POLYGON ((15.95045105500003 -3.930469643999970...,625264,619080,1244344,1119909.6,0,0.00,1.100173e+06,9.901554e+05
10,10,10,Kongo Central,POLYGON ((14.412763440000049 -4.31460007499993...,241942,239549,481491,433341.9,0,0.00,4.320742e+05,3.888667e+05
11,11,11,Kwango,POLYGON ((17.612207280000064 -4.23313797699995...,188404,186540,374944,337449.6,11,10.45,3.320121e+05,2.988109e+05
12,12,12,Kwilu,POLYGON ((17.39747016000007 -3.198059929999942...,358822,355273,714095,642685.5,275,261.25,6.316336e+05,5.684702e+05
13,13,13,Lomami,POLYGON ((25.00325141600007 -4.865323929999931...,333382,330085,663467,597120.3,400441,380418.95,5.869494e+05,5.282544e+05
14,14,14,Lualaba,POLYGON ((21.96283752000005 -7.699764337999966...,320781,317609,638390,574551.0,1457,1384.15,5.650167e+05,5.085150e+05
15,15,15,Maniema,POLYGON ((26.077619559000027 -0.03658012999994...,245616,243187,488803,439922.7,240,228.00,4.322061e+05,3.889855e+05
16,16,16,Maï-Ndombe,POLYGON ((19.15472772000004 -0.822036873999934...,136263,134915,271178,244060.2,2593,2463.35,2.413297e+05,2.171967e+05
17,17,17,Mongala,POLYGON ((22.715724600000044 3.127645951000033...,184548,182723,367271,330543.9,0,0.00,3.254643e+05,2.929179e+05
18,18,18,Nord-Kivu,POLYGON ((29.862567330000047 0.950517959000023...,749232,741822,1491054,1341948.6,2780,2641.00,1.333577e+06,1.200219e+06
19,19,19,Nord-Ubangi,POLYGON ((19.602000000000032 5.131999929000074...,125705,124462,250167,225150.3,0,0.00,2.213031e+05,1.991728e+05
20,20,20,Sankuru,POLYGON ((23.99544736200005 -1.701364548999947...,15848,15692,31540,28386.0,1026,974.70,2.758267e+04,2.482441e+04
21,21,21,Sud-Kivu,POLYGON ((29.050726462000057 -1.58385127299993...,499475,494535,994010,894609.0,750073,712569.35,8.862046e+05,7.975842e+05
22,22,22,Sud-Ubangi,POLYGON ((19.072905372000037 4.775668451000058...,240772,238390,479162,431245.8,0,0.00,4.244415e+05,3.819973e+05
23,23,23,Tanganyika,POLYGON ((26.968362159000037 -4.99952056799998...,443014,438632,881646,793481.4,1388,1318.60,7.803881e+05,7.023493e+05
24,24,24,Tshopo,"POLYGON ((23.59907575400007 2.201843183000051,...",281653,278867,560520,504468.0,32,30.40,4.963490e+05,4.467141e+05
25,25,25,Tshuapa,POLYGON ((22.127389918000063 1.762617137000063...,134392,133063,267455,240709.5,2,1.90,2.361794e+05,2.125614e+05

Read charity provided estimates

In [83]:
drc_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI DRC")
drc_hki_data

      Admin_level1  Submitted HKI Data for Target Population in 2021(Round2)
0    Kongo Central                                         739193.000
1         Kinshasa                                        1745775.000
2   Kasai Oriental                                            928.908
3         Bas Uele                                         251345.000
4         Equateur                                         458908.000
5     Haut Katanga                                        1157024.000
6      Haut Lomami                                         745779.000
7        Haut Uele                                         384125.000
8            Ituri                                        1308159.000
9            Kasai                                         855151.000
10          Kwango                                         454463.000
11           Kwilu                                         990478.000
12   Kasai Central                                         906003.000
13         Lualaba                                         505694.000
14          Lomami                                         696391.000
15       Maindombe                                         376996.000
16         Mongala                                         483629.000
17         Maniema                                         511442.000
18       Nord Kivu                                        1657958.000
19     Nord Ubangi                                         280213.000
20        Sud Kivu                                        1341471.000
21         Sankuru                                         444172.000
22      Sud Ubangi                                         572379.000
23      Tanganyika                                         547839.000
24          Tshopo                                         642034.000
25         Tshuapa                                         393373.000
26           Total                                                NaN

Rename column names

In [84]:
drc_hki_output=drc_hki_output.rename(columns={"ADM1_FR":"Admin_level1"})

Use concat to combine

In [85]:
drc_hki_merged  =  pd.merge(drc_hki_data, drc_hki_output, on=["Admin_level1"])
drc_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'Unnamed: 0.1', 'Unnamed: 0', 'geometry',
       'worldpop_cons_u5_cod_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_cod_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months',
       'cod_children_under_five_2020', 'facebook_6-59_months'],
      dtype='object')

Calculate percentage differences

In [86]:
drc_hki_merged["cons_perc_difference"]  = ((drc_hki_merged["worldpop_cons_6-59_months"]  - drc_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  drc_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])
drc_hki_merged["wopr_perc_difference"]  = ((drc_hki_merged["worldpop_wopr_6-59_months"]  -  drc_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  drc_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])
drc_hki_merged["meta_perc_difference"]  = ((drc_hki_merged["facebook_6-59_months"]  - drc_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  drc_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])

Save to file

In [87]:
drc_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'Unnamed: 0.1', 'Unnamed: 0', 'geometry',
       'worldpop_cons_u5_cod_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_cod_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months',
       'cod_children_under_five_2020', 'facebook_6-59_months',
       'cons_perc_difference', 'wopr_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [88]:
ordered_col_names=[
        'Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'worldpop_wopr_6-59_months', 
       'wopr_perc_difference',
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [89]:
drc_hki_merged  =  drc_hki_merged[ordered_col_names]
drc_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round2),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Kongo Central,739193.000,433341.9,-0.413764,0.00,-1.000000,388866.745673,-0.473931
1,Kinshasa,1745775.000,1119909.6,-0.358503,0.00,-1.000000,990155.363971,-0.432828
2,Kasai Oriental,928.908,814854.6,876.217765,310040.10,332.768360,719396.123455,773.453577
3,Equateur,458908.000,343492.2,-0.251501,0.00,-1.000000,310573.569864,-0.323233
4,Ituri,1308159.000,893045.7,-0.317326,668894.05,-0.488675,790111.352478,-0.396013
5,Kwango,454463.000,337449.6,-0.257476,10.45,-0.999977,298810.870958,-0.342497
6,Kwilu,990478.000,642685.5,-0.351136,261.25,-0.999736,568470.196000,-0.426065
7,Lualaba,505694.000,574551.0,0.136163,1384.15,-0.997263,508514.999786,0.005578
8,Lomami,696391.000,597120.3,-0.142550,380418.95,-0.453728,528254.421752,-0.241440
9,Mongala,483629.000,330543.9,-0.316534,0.00,-1.000000,292917.900673,-0.394333
10,Maniema,511442.000,439922.7,-0.139839,228.00,-0.999554,388985.459242,-0.239434
11,Sankuru,444172.000,28386.0,-0.936092,974.70,-0.997806,24824.405550,-0.944111
12,Tanganyika,547839.000,793481.4,0.448384,1318.60,-0.997593,702349.329310,0.282036
13,Tshopo,642034.000,504468.0,-0.214266,30.40,-0.999953,446714.106665,-0.304220
14,Tshuapa,393373.000,240709.5,-0.388088,1.90,-0.999995,212561.439906,-0.459644

In [90]:
drc_hki_merged.to_excel(writer ,sheet_name="HKI_DRC",index=False)

####  Mali

Read outputs

In [91]:
mali_hki_output= pd.read_csv(input2_path/ "clean_hki_mali_output.csv")
mali_hki_output

,Unnamed: 0.1,Unnamed: 0,ADM1_FR,geometry,worldpop_cons_u5_mli_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_mli_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,mli_children_under_five_2020,facebook_6-59_months
0,0,0,Bamako,POLYGON ((-7.929383644999973 12.68170913700004...,286076,279613,565689,509120.1,464306,441090.70,429775.046345,386797.541711
1,1,1,Gao,POLYGON ((0.3757176060000234 18.05625935200004...,74516,72832,147348,132613.2,147196,139836.20,136147.347021,122532.612319
2,2,2,Kayes,POLYGON ((-9.330083152999975 15.49779234900006...,264223,258252,522475,470227.5,570560,542032.00,504231.719318,453808.547386
3,3,3,Kidal,POLYGON ((1.2012791060000723 20.72027135400003...,12580,12296,24876,22388.4,11393,10823.35,20339.338018,18305.404216
4,4,4,Koulikoro,POLYGON ((-9.000381902999948 15.49747959900003...,408579,399347,807926,727133.4,894384,849664.80,726177.120770,653559.408693
5,5,5,Menaka,POLYGON ((2.2474526070000707 18.05950322700005...,7694,7520,15214,13692.6,17196,16336.20,13525.476048,12172.928443
6,6,6,Mopti,POLYGON ((-3.2365822729999536 15.8573512250000...,256930,251125,508055,457249.5,632888,601243.60,463923.530391,417531.177352
7,7,7,Sikasso,POLYGON ((-5.114929024999981 12.65576372200007...,362575,354382,716957,645261.3,717957,682059.15,697597.584364,627837.825928
8,8,8,Segou,POLYGON ((-5.3301601499999265 15.4961487240000...,299269,292507,591776,532598.4,689670,655186.50,548203.473807,493383.126426
9,9,9,Tombouctou,POLYGON ((-4.833489648999944 24.99951198300004...,98026,95811,193837,174453.3,195439,185667.05,175890.362845,158301.326560

Read charity provided estimates

In [92]:
mali_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Mali")

In [93]:
mali_hki_data=mali_hki_data[["Admin_level1","Submitted HKI Data for Target Population in 2021(Round 1 and 2)"]]
mali_hki_data

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round 1 and 2)
0,Kayes,803253
1,Segou,949223
2,Bamako,1971583
3,Koulikoro,1230195
4,Sikasso,1272457
5,Mopti,896758
6,Gao,225744
7,Kidal,11351
8,Menaka,47013
9,Tombouctou,191328
10,Taoudeni,40802

Rename column names

In [94]:
mali_hki_output  =  mali_hki_output.rename(columns={"ADM1_FR":"Admin_level1"})

Use concat to combine

In [95]:
mali_hki_merged  =  pd.merge(mali_hki_data, mali_hki_output, on=["Admin_level1"])

Calculate percentage differences

In [96]:
mali_hki_merged["cons_perc_difference"]  = ((mali_hki_merged["worldpop_cons_6-59_months"]  - mali_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])  /  mali_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])
mali_hki_merged["wopr_perc_difference"]  = ((mali_hki_merged["worldpop_wopr_6-59_months"]  -  mali_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])  /  mali_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])
mali_hki_merged["meta_perc_difference"]  = ((mali_hki_merged["facebook_6-59_months"]  - mali_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])  /  mali_hki_merged["Submitted HKI Data for Target Population in 2021(Round 1 and 2)"])

Save to file

In [97]:
mali_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round 1 and 2)',
       'Unnamed: 0.1', 'Unnamed: 0', 'geometry',
       'worldpop_cons_u5_mli_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_mli_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months',
       'mli_children_under_five_2020', 'facebook_6-59_months',
       'cons_perc_difference', 'wopr_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [98]:
ordered_col_names  =  [
        'Admin_level1',
        'Submitted HKI Data for Target Population in 2021(Round 1 and 2)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'worldpop_wopr_6-59_months', 
       'wopr_perc_difference',
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [99]:
mali_hki_merged=mali_hki_merged[ordered_col_names]
mali_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round 1 and 2),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Kayes,803253,470227.5,-0.414596,542032.00,-0.325204,453808.547386,-0.435037
1,Segou,949223,532598.4,-0.438911,655186.50,-0.309765,493383.126426,-0.480224
2,Bamako,1971583,509120.1,-0.741771,441090.70,-0.776276,386797.541711,-0.803814
3,Koulikoro,1230195,727133.4,-0.408928,849664.80,-0.309325,653559.408693,-0.468735
4,Sikasso,1272457,645261.3,-0.492901,682059.15,-0.463983,627837.825928,-0.506594
5,Mopti,896758,457249.5,-0.490108,601243.60,-0.329536,417531.177352,-0.534399
6,Gao,225744,132613.2,-0.412550,139836.20,-0.380554,122532.612319,-0.457205
7,Kidal,11351,22388.4,0.972372,10823.35,-0.046485,18305.404216,0.612669
8,Menaka,47013,13692.6,-0.708749,16336.20,-0.652517,12172.928443,-0.741073
9,Tombouctou,191328,174453.3,-0.088198,185667.05,-0.029588,158301.326560,-0.172618

In [100]:
mali_hki_merged.to_excel(writer ,sheet_name="HKI_Mali",index=False)

####  Niger

Read outputs

In [101]:
niger_hki_output= pd.read_csv(input2_path/ "clean_hki_niger_output.csv")
niger_hki_output

,Unnamed: 0.1,Unnamed: 0,adm_01,geometry,worldpop_cons_u5_ner_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_ner_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,ner_children_under_five_2020,facebook_6-59_months
0,0,0,Agadez,POLYGON ((11.989007050000055 23.53318620400006...,70584,72906,143490,129141.0,113887,108192.65,1.272814e+05,1.145533e+05
1,1,1,Diffa,POLYGON ((15.559419827000056 18.00624677600007...,94292,97394,191686,172517.4,156003,148202.85,1.901520e+05,1.711368e+05
2,2,2,Dosso,POLYGON ((3.6684016160000397 11.98401484300006...,270945,279858,550803,495722.7,544313,517097.35,5.286057e+05,4.757452e+05
3,3,3,Maradi,"POLYGON ((7.769470215000069 14.42108154300007,...",490176,506300,996476,896828.4,1080606,1026575.70,1.066943e+06,9.602486e+05
4,4,4,Niamey,POLYGON ((2.0944824220000555 13.61968994100004...,141960,146630,288590,259731.0,212294,201679.30,2.301063e+05,2.070957e+05
5,5,5,Tahoua,"POLYGON ((4.871293319000074 18.67932348100004,...",529446,546863,1076309,968678.1,936037,889235.15,1.093356e+06,9.840205e+05
6,6,6,Tillaberi,POLYGON ((3.881286621000072 15.689086914000029...,381942,394506,776448,698803.2,737947,701049.65,7.455088e+05,6.709580e+05
7,7,7,Zinder,POLYGON ((12.004882812000062 17.41851806600004...,550566,568677,1119243,1007318.7,1067443,1014070.85,1.186336e+06,1.067702e+06

Read charity provided estimates

In [102]:
niger_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Niger")

In [103]:
niger_hki_data=niger_hki_data[["Admin_level1","Submitted HKI Data for Target Population in 2021(Round2)"]]
niger_hki_data

  Admin_level1  Submitted HKI Data for Target Population in 2021(Round2)
0       Agadez                                             136908
1        Diffa                                             288900
2        Dosso                                             647530
3    Tillaberi                                             844530
4       Tahoua                                            1155112
5       Maradi                                            1339845
6       Niamey                                             334979
7       Zinder                                            1458736

Rename column names

In [104]:
niger_hki_output=niger_hki_output.rename(columns={"adm_01":"Admin_level1"})

Use concat to combine

In [105]:
niger_hki_merged=pd.merge(niger_hki_data,niger_hki_output,on=["Admin_level1"])

Calculate percentage differences

In [106]:
niger_hki_merged["cons_perc_difference"]  = ((niger_hki_merged["worldpop_cons_6-59_months"]  - niger_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  niger_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])
niger_hki_merged["wopr_perc_difference"]  = ((niger_hki_merged["worldpop_wopr_6-59_months"]  -  niger_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  niger_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])
niger_hki_merged["meta_perc_difference"]  = ((niger_hki_merged["facebook_6-59_months"]  - niger_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])  /  niger_hki_merged["Submitted HKI Data for Target Population in 2021(Round2)"])

Save to file

In [107]:
niger_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'Unnamed: 0.1', 'Unnamed: 0', 'geometry',
       'worldpop_cons_u5_ner_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_ner_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months',
       'ner_children_under_five_2020', 'facebook_6-59_months',
       'cons_perc_difference', 'wopr_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [108]:
ordered_col_names=[
        'Admin_level1',
       'Submitted HKI Data for Target Population in 2021(Round2)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'worldpop_wopr_6-59_months', 
       'wopr_perc_difference',
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [109]:
niger_hki_merged=niger_hki_merged[ordered_col_names]
niger_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(Round2),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Agadez,136908,129141.0,-0.056732,108192.65,-0.209742,1.145533e+05,-0.163283
1,Diffa,288900,172517.4,-0.402847,148202.85,-0.487010,1.711368e+05,-0.407626
2,Dosso,647530,495722.7,-0.234441,517097.35,-0.201431,4.757452e+05,-0.265292
3,Tillaberi,844530,698803.2,-0.172554,701049.65,-0.169894,6.709580e+05,-0.205525
4,Tahoua,1155112,968678.1,-0.161399,889235.15,-0.230174,9.840205e+05,-0.148117
5,Maradi,1339845,896828.4,-0.330648,1026575.70,-0.233810,9.602486e+05,-0.283314
6,Niamey,334979,259731.0,-0.224635,201679.30,-0.397934,2.070957e+05,-0.381765
7,Zinder,1458736,1007318.7,-0.309458,1014070.85,-0.304829,1.067702e+06,-0.268063

In [110]:
niger_hki_merged.to_excel(writer ,sheet_name="HKI_Niger",index=False)

####  Cote'd'Ivoire

Read outputs

In [111]:
cote_d_ivoire_hki_output= pd.read_csv(input1_path/ "hki_cote_d_ivoire_output.csv")
cote_d_ivoire_hki_output

,Unnamed: 0,ADM2_FR,ADM1_FR,geometry,worldpop_cons_u5_civ_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_civ_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,civ_children_under_five_2020,facebook_6-59_months
0,0,Abengourou,Indenie-Djuablin,"POLYGON ((-3.321438832999945 7.03456178600004,...",30414,29933,60347,54312.3,57365.908746,51629.317871
1,1,Abidjan,District Autonome D'Abidjan,"POLYGON ((-4.16992573999994 5.600407060000066,...",443063,436056,879119,791207.1,842925.342358,758632.808122
2,2,Aboisso,Sud-Comoe,"POLYGON ((-3.11099214799998 6.156107682000027,...",25280,24880,50160,45144.0,48149.914687,43334.923218
3,3,Adiaké,Sud-Comoe,POLYGON ((-3.189513444999932 5.323631549000026...,6905,6795,13700,12330.0,13375.807220,12038.226498
4,4,Adzopé,Me,POLYGON ((-3.650782883999966 6.444646703000046...,17578,17300,34878,31390.2,33495.397565,30145.857809
...,...,...,...,...,...,...,...,...,...,...
103,103,Yakassé-Attobrou,Me,POLYGON ((-3.5139098499999477 6.36396205300002...,8102,7974,16076,14468.4,15279.808335,13751.827501
104,104,Yamoussoukro,District Autonome De Yamoussoukro,POLYGON ((-5.451801156999977 7.039491285000054...,28580,28128,56708,51037.2,54216.405866,48794.765279
105,105,Zouan-Hounien,Tonkpi,POLYGON ((-8.298981007999942 7.129178140000022...,18710,18415,37125,33412.5,35697.947974,32128.153177
106,106,Zoukougbeu,Haut-Sassandra,POLYGON ((-6.890560152999967 7.051098102000026...,9835,9679,19514,17562.6,18680.153440,16812.138096
107,107,Zuénoula,Marahoue,POLYGON ((-5.971661380999933 7.747686484000042...,19943,19628,39571,35613.9,37842.823607,34058.541246

Read charity provided estimates

In [112]:
cote_d_ivoire_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Côte dIvoire")
cote_d_ivoire_hki_data.columns

Index(['ADMIN1 ',
       'Submitted HKI Data for Target Population in 2021-Round 1 &Round 2',
       'Population according to WorldPop Demographic database 2021',
       'Percentage difference',
       ' Population according to WorldPop Top Down Constrained model ',
       'Percentage difference.1', 'Population according to Facebook HRSL',
       'Percentage difference.2',
       ' Population according to WorldPop Bottom-Up ',
       'Percentage difference.3', 'Average across all alternative estimates',
       'Percentage difference.4'],
      dtype='object')

In [113]:
cote_d_ivoire_hki_data=cote_d_ivoire_hki_data[["ADMIN1 ","Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"]]
# cote_d_ivoire_hki_data2=cote_d_ivoire_hki_data[["Communes*","Submitted HKI Data for Target Population in 2021(SVA ROUTIN-after round1 &2)"]]
cote_d_ivoire_hki_data

,ADMIN1,Submitted HKI Data for Target Population in 2021-Round 1 &Round 2
0,Abobo-Est,330924
1,Abobo-Ouest,327839
2,Adzopé,57417
3,Agboville,82519
4,Akoupé,49429
...,...,...
67,Koro,15657
68,Kouto,42938
69,Ouaninou,13810
70,Touba,23852
71,Toulepleu,18834

Rename column names

In [114]:
cote_d_ivoire_hki_data = cote_d_ivoire_hki_data.rename(columns={"ADMIN1 ": "Admin_level2"})

In [115]:
cote_d_ivoire_hki_output  =  cote_d_ivoire_hki_output.rename(columns={"ADM1_FR":"Admin_level1", "ADM2_FR" : "Admin_level2" })
cote_d_ivoire_hki_output

,Unnamed: 0,Admin_level2,Admin_level1,geometry,worldpop_cons_u5_civ_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_civ_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,civ_children_under_five_2020,facebook_6-59_months
0,0,Abengourou,Indenie-Djuablin,"POLYGON ((-3.321438832999945 7.03456178600004,...",30414,29933,60347,54312.3,57365.908746,51629.317871
1,1,Abidjan,District Autonome D'Abidjan,"POLYGON ((-4.16992573999994 5.600407060000066,...",443063,436056,879119,791207.1,842925.342358,758632.808122
2,2,Aboisso,Sud-Comoe,"POLYGON ((-3.11099214799998 6.156107682000027,...",25280,24880,50160,45144.0,48149.914687,43334.923218
3,3,Adiaké,Sud-Comoe,POLYGON ((-3.189513444999932 5.323631549000026...,6905,6795,13700,12330.0,13375.807220,12038.226498
4,4,Adzopé,Me,POLYGON ((-3.650782883999966 6.444646703000046...,17578,17300,34878,31390.2,33495.397565,30145.857809
...,...,...,...,...,...,...,...,...,...,...
103,103,Yakassé-Attobrou,Me,POLYGON ((-3.5139098499999477 6.36396205300002...,8102,7974,16076,14468.4,15279.808335,13751.827501
104,104,Yamoussoukro,District Autonome De Yamoussoukro,POLYGON ((-5.451801156999977 7.039491285000054...,28580,28128,56708,51037.2,54216.405866,48794.765279
105,105,Zouan-Hounien,Tonkpi,POLYGON ((-8.298981007999942 7.129178140000022...,18710,18415,37125,33412.5,35697.947974,32128.153177
106,106,Zoukougbeu,Haut-Sassandra,POLYGON ((-6.890560152999967 7.051098102000026...,9835,9679,19514,17562.6,18680.153440,16812.138096
107,107,Zuénoula,Marahoue,POLYGON ((-5.971661380999933 7.747686484000042...,19943,19628,39571,35613.9,37842.823607,34058.541246

In [116]:
# cote_d_ivoire_hki_data2 = cote_d_ivoire_hki_data2.rename(columns={"Communes*": "Admin_level2"})

Use concat to combine

In [117]:
cote_d_ivoire_hki_merged  =  pd.merge(cote_d_ivoire_hki_data, cote_d_ivoire_hki_output, on=["Admin_level2"])
# cote_d_ivoire_hki_merged

In [118]:
cote_d_ivoire_hki_merged.columns

Index(['Admin_level2',
       'Submitted HKI Data for Target Population in 2021-Round 1 &Round 2',
       'Unnamed: 0', 'Admin_level1', 'geometry',
       'worldpop_cons_u5_civ_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_civ_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'civ_children_under_five_2020', 'facebook_6-59_months'],
      dtype='object')

Calculate percentage differences

In [119]:
cote_d_ivoire_hki_merged["cons_perc_difference"]  = ((cote_d_ivoire_hki_merged["worldpop_cons_6-59_months"]  - cote_d_ivoire_hki_merged["Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"])  /  cote_d_ivoire_hki_merged["Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"])
# cote_d_ivoire_hki_merged["wopr_perc_difference"]  = ((cote_d_ivoire_hki_merged["worldpop_wopr_6-59_months"]  -  cote_d_ivoire_hki_merged["Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"])  /  cote_d_ivoire_hki_merged["Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"])
cote_d_ivoire_hki_merged["meta_perc_difference"]  = ((cote_d_ivoire_hki_merged["facebook_6-59_months"]  - cote_d_ivoire_hki_merged["Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"])  /  cote_d_ivoire_hki_merged["Submitted HKI Data for Target Population in 2021-Round 1 &Round 2"])

Save to file

In [120]:
cote_d_ivoire_hki_merged.columns

Index(['Admin_level2',
       'Submitted HKI Data for Target Population in 2021-Round 1 &Round 2',
       'Unnamed: 0', 'Admin_level1', 'geometry',
       'worldpop_cons_u5_civ_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_civ_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'civ_children_under_five_2020', 'facebook_6-59_months',
       'cons_perc_difference', 'meta_perc_difference'],
      dtype='object')

In [121]:
ordered_col_names  =  [
        'Admin_level2',
        'Submitted HKI Data for Target Population in 2021-Round 1 &Round 2',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [122]:
cote_d_ivoire_hki_merged  =  cote_d_ivoire_hki_merged[ordered_col_names]
cote_d_ivoire_hki_merged

,Admin_level2,Submitted HKI Data for Target Population in 2021-Round 1 &Round 2,worldpop_cons_6-59_months,cons_perc_difference,facebook_6-59_months,meta_perc_difference
0,Adzopé,57417,31390.2,-0.453294,30145.857809,-0.474966
1,Agboville,82519,45661.5,-0.446655,43579.271542,-0.471888
2,Akoupé,49429,18718.2,-0.621311,17864.486622,-0.638583
3,Alépé,30280,22506.3,-0.256727,22427.236621,-0.259338
4,Bangolo,88698,63428.4,-0.284895,60962.962866,-0.312691
5,Béoumi,46670,24477.3,-0.475524,23514.602730,-0.496152
6,Biankouma,63793,24337.8,-0.618488,23038.988276,-0.638848
7,Bondoukou,71030,54203.4,-0.236894,52148.038550,-0.265831
8,Botro,24019,13256.1,-0.448099,12664.708139,-0.472721
9,Dabou,54004,21927.6,-0.593963,21125.940886,-0.608808
10,Danané,98465,43506.0,-0.558158,41955.601705,-0.573903
11,Duékoué,143969,77752.8,-0.459934,73915.709856,-0.486586
12,Grand-Lahou,43404,26242.2,-0.395397,25732.983694,-0.407129
13,Kani,26455,12421.8,-0.530455,11879.385633,-0.550959
14,Koun Fao,36570,17418.6,-0.523692,16657.759158,-0.544497
15,Madinani,19482,6506.1,-0.666046,6226.340595,-0.680405
16,Man,102198,56473.2,-0.447414,54069.312503,-0.470936
17,Sakassou,26040,14852.7,-0.429620,14225.598653,-0.453702
18,Sandegue,12551,8478.9,-0.324444,8052.028620,-0.358455
19,Séguéla,65839,33698.7,-0.488165,32212.059271,-0.510745
20,Sikensi,26387,12775.5,-0.515841,12183.652284,-0.538271
21,Tanda,25722,12009.6,-0.533100,11596.678799,-0.549153
22,Tiassalé,64619,26284.5,-0.593239,25035.576129,-0.612566
23,Transua,24682,13492.8,-0.453334,12903.779032,-0.477199
24,Abengourou,132600,54312.3,-0.590405,51629.317871,-0.610639
25,Aboisso,84438,45144.0,-0.465359,43334.923218,-0.486784
26,Adiaké,19296,12330.0,-0.361007,12038.226498,-0.376128
27,Agnibilékrou,53167,28750.5,-0.459242,27429.597103,-0.484086
28,Bocanda,30407,22941.9,-0.245506,22071.892147,-0.274118
29,Buyo,96827,30093.3,-0.689205,28749.241471,-0.703087
30,Daloa,245748,95591.7,-0.611017,91412.239115,-0.628024
31,Dimbokro,24516,14029.2,-0.427753,13263.906310,-0.458969
32,Divo,145408,66125.7,-0.545240,63177.294775,-0.565517
33,Fresco,37796,14898.6,-0.605815,14357.904439,-0.620121
34,Guitry,57221,22581.0,-0.605372,21432.116456,-0.625450
35,Lakota,76467,32774.4,-0.571392,31579.211654,-0.587022
36,Méagui,149005,34476.3,-0.768623,33033.026647,-0.778309
37,Oumé,62134,46685.7,-0.248629,44782.215501,-0.279264
38,Sassandra,89500,56312.1,-0.370815,53822.504781,-0.398631
39,Soubré,199892,100896.3,-0.495246,96512.131122,-0.517179
40,Tabou,54706,31167.0,-0.430282,29499.901409,-0.460756
41,Tiapoum,16036,12488.4,-0.221227,12932.236652,-0.193550
42,Toumodi,31138,20120.4,-0.353831,19181.659721,-0.383979
43,Zoukougbeu,54218,17562.6,-0.676074,16812.138096,-0.689916
44,Zuénoula,73288,35613.9,-0.514056,34058.541246,-0.535278
45,Bloléquin,40250,19839.6,-0.507091,18869.956709,-0.531181
46,Boundiali,44309,21131.1,-0.523097,20224.672524,-0.543554
47,Daoukro,45357,26261.1,-0.421013,25143.946409,-0.445644
48,Katiola,32161,17611.2,-0.452405,16876.639445,-0.475245
49,Koro,15657,9210.6,-0.411726,8850.292433,-0.434739
50,Kouto,42938,22167.0,-0.483744,21222.576242,-0.505739
51,Ouaninou,13810,7648.2,-0.446184,7399.356500,-0.464203
52,Touba,23852,12548.7,-0.473893,12007.474351,-0.496584
53,Toulepleu,18834,8425.8,-0.552628,8235.442675,-0.562735

In [123]:
cote_d_ivoire_hki_merged.to_excel(writer, sheet_name="HKI_Cote dIvoire", index=False)

####  Burkina Faso

Read outputs

In [124]:
burkinafaso_hki_output= pd.read_csv(input1_path/ "hki_burkina_faso_output.csv")
burkinafaso_hki_output

,ADM1_FR,worldpop_cons_u5_bfa_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_bfa_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,facebook_u5_sum,facebook_6-59_months
0,Boucle du Mouhoun,155894,150774,306668,276001.2,307749,292361.55,323142,290827.8
1,Cascades,91047,88057,179104,161193.6,131510,124934.50,183375,165037.5
2,Centre,340002,328837,668839,601955.1,490513,465987.35,505661,455094.9
3,Centre-Est,136239,131765,268004,241203.6,255829,243037.55,286884,258195.6
4,Centre-Nord,140212,135608,275820,248238.0,303443,288270.85,299022,269119.8
5,Centre-Ouest,137553,133035,270588,243529.2,268718,255282.10,273554,246198.6
6,Centre-Sud,71235,68895,140130,126117.0,127668,121284.60,138916,125024.4
7,Est,163718,158342,322060,289854.0,314472,298748.40,386277,347649.3
8,Hauts-Bassins,198771,192243,391014,351912.6,362552,344424.40,382311,344079.9
9,Nord,128313,124099,252412,227170.8,278750,264812.50,261891,235701.9
10,Plateau-Central,75303,72830,148133,133319.7,158403,150482.85,154039,138635.1
11,Sahel,118631,114736,233367,210030.3,177756,168868.20,243695,219325.5
12,Sud-Ouest,74928,72467,147395,132655.5,141703,134617.85,146285,131656.5

Read charity provided estimates

In [125]:
burkinafaso_hki_data=pd.read_excel(path /"Data" / "GiveWell Charity Submitted Data.xlsx",sheet_name="HKI Burkina Faso")
burkinafaso_hki_data.columns

Index(['Region*', 'Submitted HKI Data for Target Population in 2021(round 1)',
       'Region*.1',
       'Submitted HKI Data for Target Population in 2021(round 2)',
       'Population according to WorldPop Demographic database 2021',
       'Percentage difference',
       ' Population according to WorldPop Top Down Constrained model ',
       'Percentage difference.1', 'Population according to Facebook HRSL',
       'Percentage difference.2',
       ' Population according to WorldPop Bottom-Up ',
       'Percentage difference.3', 'Average across all alternative estimates',
       'Percentage difference.4'],
      dtype='object')

In [126]:
burkinafaso_hki_data=burkinafaso_hki_data[["Region*","Submitted HKI Data for Target Population in 2021(round 2)"]]
burkinafaso_hki_data

,Region*,Submitted HKI Data for Target Population in 2021(round 2)
0,Boucle du Mouhoun,340955
1,Centre,138102
2,Centre-Nord,380936
3,Est,286912
4,Nord,305243
5,Sahel,283016
6,Centre-Ouest,146891
7,Centre-Sud,339817
8,Hauts-Bassins,324745
9,Plateau-Central,291458
10,Sud-Ouest,166145
11,Centre-Est,239819
12,Cascades,149704

Rename column names

In [127]:
burkinafaso_hki_output=burkinafaso_hki_output.rename(columns={"ADM1_FR":"Admin_level1"})
burkinafaso_hki_data  =  burkinafaso_hki_data.rename(columns= {"Region*": "Admin_level1" })

Use concat to combine

In [128]:
burkinafaso_hki_merged=pd.merge(burkinafaso_hki_data,burkinafaso_hki_output,on=["Admin_level1"])
burkinafaso_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(round 2),worldpop_cons_u5_bfa_f_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_bfa_m_0_4_2022_1km_UNadj_constrained_sum,worldpop_cons_u5_sum_total,worldpop_cons_6-59_months,worldpop_wopr_u5_sum,worldpop_wopr_6-59_months,facebook_u5_sum,facebook_6-59_months
0,Boucle du Mouhoun,340955,155894,150774,306668,276001.2,307749,292361.55,323142,290827.8
1,Centre,138102,340002,328837,668839,601955.1,490513,465987.35,505661,455094.9
2,Centre-Nord,380936,140212,135608,275820,248238.0,303443,288270.85,299022,269119.8
3,Est,286912,163718,158342,322060,289854.0,314472,298748.40,386277,347649.3
4,Nord,305243,128313,124099,252412,227170.8,278750,264812.50,261891,235701.9
5,Sahel,283016,118631,114736,233367,210030.3,177756,168868.20,243695,219325.5
6,Centre-Ouest,146891,137553,133035,270588,243529.2,268718,255282.10,273554,246198.6
7,Centre-Sud,339817,71235,68895,140130,126117.0,127668,121284.60,138916,125024.4
8,Hauts-Bassins,324745,198771,192243,391014,351912.6,362552,344424.40,382311,344079.9
9,Plateau-Central,291458,75303,72830,148133,133319.7,158403,150482.85,154039,138635.1
10,Sud-Ouest,166145,74928,72467,147395,132655.5,141703,134617.85,146285,131656.5
11,Centre-Est,239819,136239,131765,268004,241203.6,255829,243037.55,286884,258195.6
12,Cascades,149704,91047,88057,179104,161193.6,131510,124934.50,183375,165037.5

Calculate percentage differences

In [129]:
burkinafaso_hki_merged["cons_perc_difference"]  = ((burkinafaso_hki_merged["worldpop_cons_6-59_months"]  - burkinafaso_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])  /  burkinafaso_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])
burkinafaso_hki_merged["wopr_perc_difference"]  = ((burkinafaso_hki_merged["worldpop_wopr_6-59_months"]  -  burkinafaso_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])  /  burkinafaso_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])
burkinafaso_hki_merged["meta_perc_difference"]  = ((burkinafaso_hki_merged["facebook_6-59_months"]  - burkinafaso_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])  /  burkinafaso_hki_merged["Submitted HKI Data for Target Population in 2021(round 2)"])

Save to file

In [130]:
burkinafaso_hki_merged.columns

Index(['Admin_level1',
       'Submitted HKI Data for Target Population in 2021(round 2)',
       'worldpop_cons_u5_bfa_f_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_bfa_m_0_4_2022_1km_UNadj_constrained_sum',
       'worldpop_cons_u5_sum_total', 'worldpop_cons_6-59_months',
       'worldpop_wopr_u5_sum', 'worldpop_wopr_6-59_months', 'facebook_u5_sum',
       'facebook_6-59_months', 'cons_perc_difference', 'wopr_perc_difference',
       'meta_perc_difference'],
      dtype='object')

In [131]:
ordered_col_names=[
        'Admin_level1',
        'Submitted HKI Data for Target Population in 2021(round 2)',
       'worldpop_cons_6-59_months',
       'cons_perc_difference',    
       'worldpop_wopr_6-59_months', 
       'wopr_perc_difference',
       'facebook_6-59_months', 
       'meta_perc_difference' 
 ]

In [132]:
burkinafaso_hki_merged=burkinafaso_hki_merged[ordered_col_names]
burkinafaso_hki_merged

,Admin_level1,Submitted HKI Data for Target Population in 2021(round 2),worldpop_cons_6-59_months,cons_perc_difference,worldpop_wopr_6-59_months,wopr_perc_difference,facebook_6-59_months,meta_perc_difference
0,Boucle du Mouhoun,340955,276001.2,-0.190505,292361.55,-0.142522,290827.8,-0.147020
1,Centre,138102,601955.1,3.358772,465987.35,2.374226,455094.9,2.295353
2,Centre-Nord,380936,248238.0,-0.348347,288270.85,-0.243256,269119.8,-0.293530
3,Est,286912,289854.0,0.010254,298748.40,0.041254,347649.3,0.211693
4,Nord,305243,227170.8,-0.255771,264812.50,-0.132453,235701.9,-0.227822
5,Sahel,283016,210030.3,-0.257885,168868.20,-0.403326,219325.5,-0.225042
6,Centre-Ouest,146891,243529.2,0.657891,255282.10,0.737902,246198.6,0.676063
7,Centre-Sud,339817,126117.0,-0.628868,121284.60,-0.643088,125024.4,-0.632083
8,Hauts-Bassins,324745,351912.6,0.083658,344424.40,0.060600,344079.9,0.059539
9,Plateau-Central,291458,133319.7,-0.542577,150482.85,-0.483689,138635.1,-0.524339
10,Sud-Ouest,166145,132655.5,-0.201568,134617.85,-0.189757,131656.5,-0.207581
11,Centre-Est,239819,241203.6,0.005774,243037.55,0.013421,258195.6,0.076627
12,Cascades,149704,161193.6,0.076749,124934.50,-0.165457,165037.5,0.102425

In [133]:
burkinafaso_hki_merged.to_excel(writer ,sheet_name="HKI_Burkina Faso",index=False)

# Close

In [134]:
writer.close()